<?php
// This script and data application were generated by AppGini 5.82
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/bacs_du_site.php");
	include("$currDir/bacs_du_site_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('bacs_du_site');
	if(!$perm[0]) {
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "bacs_du_site";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = array(
		"`bacs_du_site`.`id`" => "id",
		"IF(    CHAR_LENGTH(`site_compostage1`.`nom_du_site`), CONCAT_WS('',   `site_compostage1`.`nom_du_site`), '') /* Appartient au site */" => "appartient_site",
		"`bacs_du_site`.`type_de_bacs`" => "type_de_bacs",
		"`bacs_du_site`.`niveau_de_remplissage`" => "niveau_de_remplissage",
		"`bacs_du_site`.`Commentaires`" => "Commentaires",
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(
		1 => '`bacs_du_site`.`id`',
		2 => '`site_compostage1`.`nom_du_site`',
		3 => 3,
		4 => 4,
		5 => 5,
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = array(
		"`bacs_du_site`.`id`" => "id",
		"IF(    CHAR_LENGTH(`site_compostage1`.`nom_du_site`), CONCAT_WS('',   `site_compostage1`.`nom_du_site`), '') /* Appartient au site */" => "appartient_site",
		"`bacs_du_site`.`type_de_bacs`" => "type_de_bacs",
		"`bacs_du_site`.`niveau_de_remplissage`" => "niveau_de_remplissage",
		"`bacs_du_site`.`Commentaires`" => "Commentaires",
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters = array(
		"`bacs_du_site`.`id`" => "ID",
		"IF(    CHAR_LENGTH(`site_compostage1`.`nom_du_site`), CONCAT_WS('',   `site_compostage1`.`nom_du_site`), '') /* Appartient au site */" => "Appartient au site",
		"`bacs_du_site`.`type_de_bacs`" => "Type de bacs",
		"`bacs_du_site`.`niveau_de_remplissage`" => "Niveau de remplissage",
		"`bacs_du_site`.`Commentaires`" => "Commentaires",
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS = array(
		"`bacs_du_site`.`id`" => "id",
		"IF(    CHAR_LENGTH(`site_compostage1`.`nom_du_site`), CONCAT_WS('',   `site_compostage1`.`nom_du_site`), '') /* Appartient au site */" => "appartient_site",
		"`bacs_du_site`.`type_de_bacs`" => "type_de_bacs",
		"`bacs_du_site`.`niveau_de_remplissage`" => "niveau_de_remplissage",
		"`bacs_du_site`.`Commentaires`" => "Commentaires",
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array('appartient_site' => 'Appartient au site', );

	$x->QueryFrom = "`bacs_du_site` LEFT JOIN `site_compostage` as site_compostage1 ON `site_compostage1`.`id`=`bacs_du_site`.`appartient_site` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = false;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 0;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "bacs_du_site_view.php";
	$x->RedirectAfterInsert = "bacs_du_site_view.php?SelectedID=#ID#";
	$x->TableTitle = "Bacs du site";
	$x->TableIcon = "resources/table_icons/recycle_bag.png";
	$x->PrimaryKey = "`bacs_du_site`.`id`";

	$x->ColWidth   = array(  150, 150, 150);
	$x->ColCaption = array("Appartient au site", "Type de bacs", "Niveau de remplissage");
	$x->ColFieldName = array('appartient_site', 'type_de_bacs', 'niveau_de_remplissage');
	$x->ColNumber  = array(2, 3, 4);

	// template paths below are based on the app main directory
	$x->Template = 'templates/bacs_du_site_templateTV.html';
	$x->SelectedTemplate = 'templates/bacs_du_site_templateTVS.html';
	$x->TemplateDV = 'templates/bacs_du_site_templateDV.html';
	$x->TemplateDVP = 'templates/bacs_du_site_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HighlightColor = '#FFF0C2';
	$x->HasCalculatedFields = false;

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))) { $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])) { // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `bacs_du_site`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='bacs_du_site' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])) { // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `bacs_du_site`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='bacs_du_site' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3) { // view all
		// no further action
	}elseif($perm[2]==0) { // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`bacs_du_site`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: bacs_du_site_init
	$render=TRUE;
	if(function_exists('bacs_du_site_init')) {
		$args=array();
		$render=bacs_du_site_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: bacs_du_site_header
	$headerCode='';
	if(function_exists('bacs_du_site_header')) {
		$args=array();
		$headerCode=bacs_du_site_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode) {
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: bacs_du_site_footer
	$footerCode='';
	if(function_exists('bacs_du_site_footer')) {
		$args=array();
		$footerCode=bacs_du_site_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode) {
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>