<?php

// Data functions (insert, update, delete, form) for table bacs_du_site

// This script and data application were generated by AppGini 5.82
// Download AppGini for free from https://bigprof.com/appgini/download/

function bacs_du_site_insert() {
	global $Translation;

	// mm: can member insert record?
	$arrPerm = getTablePermissions('bacs_du_site');
	if(!$arrPerm[1]) return false;

	$data = array();
	$data['appartient_site'] = $_REQUEST['appartient_site'];
		if($data['appartient_site'] == empty_lookup_value) { $data['appartient_site'] = ''; }
	$data['type_de_bacs'] = $_REQUEST['type_de_bacs'];
		if($data['type_de_bacs'] == empty_lookup_value) { $data['type_de_bacs'] = ''; }
	$data['niveau_de_remplissage'] = $_REQUEST['niveau_de_remplissage'];
		if($data['niveau_de_remplissage'] == empty_lookup_value) { $data['niveau_de_remplissage'] = ''; }
	$data['Commentaires'] = $_REQUEST['Commentaires'];
		if($data['Commentaires'] == empty_lookup_value) { $data['Commentaires'] = ''; }

	// hook: bacs_du_site_before_insert
	if(function_exists('bacs_du_site_before_insert')) {
		$args = array();
		if(!bacs_du_site_before_insert($data, getMemberInfo(), $args)) { return false; }
	}

	$error = '';
	// set empty fields to NULL
	$data = array_map(function($v) { return ($v === '' ? NULL : $v); }, $data);
	insert('bacs_du_site', backtick_keys_once($data), $error);
	if($error)
		die("{$error}<br><a href=\"#\" onclick=\"history.go(-1);\">{$Translation['< back']}</a>");

	$recID = db_insert_id(db_link());

	// hook: bacs_du_site_after_insert
	if(function_exists('bacs_du_site_after_insert')) {
		$res = sql("select * from `bacs_du_site` where `id`='" . makeSafe($recID, false) . "' limit 1", $eo);
		if($row = db_fetch_assoc($res)) {
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args=array();
		if(!bacs_du_site_after_insert($data, getMemberInfo(), $args)) { return $recID; }
	}

	// mm: save ownership data
	set_record_owner('bacs_du_site', $recID, getLoggedMemberID());

	// if this record is a copy of another record, copy children if applicable
	if(!empty($_REQUEST['SelectedID'])) bacs_du_site_copy_children($recID, $_REQUEST['SelectedID']);

	return $recID;
}

function bacs_du_site_copy_children($destination_id, $source_id) {
	global $Translation;
	$requests = array(); // array of curl handlers for launching insert requests
	$eo = array('silentErrors' => true);
	$uploads_dir = realpath(dirname(__FILE__) . '/../' . $Translation['ImageFolder']);
	$safe_sid = makeSafe($source_id);

	// launch requests, asynchronously
	curl_batch($requests);
}

function bacs_du_site_delete($selected_id, $AllowDeleteOfParents=false, $skipChecks=false) {
	// insure referential integrity ...
	global $Translation;
	$selected_id=makeSafe($selected_id);

	// mm: can member delete record?
	$arrPerm=getTablePermissions('bacs_du_site');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='bacs_du_site' and pkValue='$selected_id'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='bacs_du_site' and pkValue='$selected_id'");
	if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3) { // allow delete?
		// delete allowed, so continue ...
	}else{
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: bacs_du_site_before_delete
	if(function_exists('bacs_du_site_before_delete')) {
		$args=array();
		if(!bacs_du_site_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'];
	}

	// child table: depots
	$res = sql("select `id` from `bacs_du_site` where `id`='$selected_id'", $eo);
	$id = db_fetch_row($res);
	$rires = sql("select count(1) from `depots` where `dans_le_bac`='".addslashes($id[0])."'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "depots", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "depots", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input type=\"button\" class=\"button\" value=\"".$Translation['yes']."\" onClick=\"window.location='bacs_du_site_view.php?SelectedID=".urlencode($selected_id)."&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input type=\"button\" class=\"button\" value=\"".$Translation['no']."\" onClick=\"window.location='bacs_du_site_view.php?SelectedID=".urlencode($selected_id)."';\">", $RetMsg);
		return $RetMsg;
	}

	// child table: intervention
	$res = sql("select `id` from `bacs_du_site` where `id`='$selected_id'", $eo);
	$id = db_fetch_row($res);
	$rires = sql("select count(1) from `intervention` where `pour_bac`='".addslashes($id[0])."'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "intervention", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "intervention", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input type=\"button\" class=\"button\" value=\"".$Translation['yes']."\" onClick=\"window.location='bacs_du_site_view.php?SelectedID=".urlencode($selected_id)."&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input type=\"button\" class=\"button\" value=\"".$Translation['no']."\" onClick=\"window.location='bacs_du_site_view.php?SelectedID=".urlencode($selected_id)."';\">", $RetMsg);
		return $RetMsg;
	}

	sql("delete from `bacs_du_site` where `id`='$selected_id'", $eo);

	// hook: bacs_du_site_after_delete
	if(function_exists('bacs_du_site_after_delete')) {
		$args=array();
		bacs_du_site_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("delete from membership_userrecords where tableName='bacs_du_site' and pkValue='$selected_id'", $eo);
}

function bacs_du_site_update($selected_id) {
	global $Translation;

	// mm: can member edit record?
	$arrPerm=getTablePermissions('bacs_du_site');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='bacs_du_site' and pkValue='".makeSafe($selected_id)."'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='bacs_du_site' and pkValue='".makeSafe($selected_id)."'");
	if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3) { // allow update?
		// update allowed, so continue ...
	}else{
		return false;
	}

	$data['appartient_site'] = makeSafe($_REQUEST['appartient_site']);
		if($data['appartient_site'] == empty_lookup_value) { $data['appartient_site'] = ''; }
	$data['type_de_bacs'] = makeSafe($_REQUEST['type_de_bacs']);
		if($data['type_de_bacs'] == empty_lookup_value) { $data['type_de_bacs'] = ''; }
	$data['niveau_de_remplissage'] = makeSafe($_REQUEST['niveau_de_remplissage']);
		if($data['niveau_de_remplissage'] == empty_lookup_value) { $data['niveau_de_remplissage'] = ''; }
	$data['Commentaires'] = makeSafe($_REQUEST['Commentaires']);
		if($data['Commentaires'] == empty_lookup_value) { $data['Commentaires'] = ''; }
	$data['selectedID'] = makeSafe($selected_id);

	// hook: bacs_du_site_before_update
	if(function_exists('bacs_du_site_before_update')) {
		$args = array();
		if(!bacs_du_site_before_update($data, getMemberInfo(), $args)) { return false; }
	}

	$o = array('silentErrors' => true);
	sql('update `bacs_du_site` set       `appartient_site`=' . (($data['appartient_site'] !== '' && $data['appartient_site'] !== NULL) ? "'{$data['appartient_site']}'" : 'NULL') . ', `type_de_bacs`=' . (($data['type_de_bacs'] !== '' && $data['type_de_bacs'] !== NULL) ? "'{$data['type_de_bacs']}'" : 'NULL') . ', `niveau_de_remplissage`=' . (($data['niveau_de_remplissage'] !== '' && $data['niveau_de_remplissage'] !== NULL) ? "'{$data['niveau_de_remplissage']}'" : 'NULL') . ', `Commentaires`=' . (($data['Commentaires'] !== '' && $data['Commentaires'] !== NULL) ? "'{$data['Commentaires']}'" : 'NULL') . " where `id`='".makeSafe($selected_id)."'", $o);
	if($o['error']!='') {
		echo $o['error'];
		echo '<a href="bacs_du_site_view.php?SelectedID='.urlencode($selected_id)."\">{$Translation['< back']}</a>";
		exit;
	}


	// hook: bacs_du_site_after_update
	if(function_exists('bacs_du_site_after_update')) {
		$res = sql("SELECT * FROM `bacs_du_site` WHERE `id`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) {
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = $data['id'];
		$args = array();
		if(!bacs_du_site_after_update($data, getMemberInfo(), $args)) { return; }
	}

	// mm: update ownership data
	sql("update `membership_userrecords` set `dateUpdated`='" . time() . "' where `tableName`='bacs_du_site' and `pkValue`='" . makeSafe($selected_id) . "'", $eo);

}

function bacs_du_site_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $ShowCancel = 0, $TemplateDV = '', $TemplateDVP = '') {
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;

	// mm: get table permissions
	$arrPerm=getTablePermissions('bacs_du_site');
	if(!$arrPerm[1] && $selected_id=='') { return ''; }
	$AllowInsert = ($arrPerm[1] ? true : false);
	// print preview?
	$dvprint = false;
	if($selected_id && $_REQUEST['dvprint_x'] != '') {
		$dvprint = true;
	}

	$filterer_appartient_site = thisOr(undo_magic_quotes($_REQUEST['filterer_appartient_site']), '');

	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: appartient_site
	$combo_appartient_site = new DataCombo;
	// combobox: type_de_bacs
	$combo_type_de_bacs = new Combo;
	$combo_type_de_bacs->ListType = 0;
	$combo_type_de_bacs->MultipleSeparator = ', ';
	$combo_type_de_bacs->ListBoxHeight = 10;
	$combo_type_de_bacs->RadiosPerLine = 1;
	if(is_file(dirname(__FILE__).'/hooks/bacs_du_site.type_de_bacs.csv')) {
		$type_de_bacs_data = addslashes(implode('', @file(dirname(__FILE__).'/hooks/bacs_du_site.type_de_bacs.csv')));
		$combo_type_de_bacs->ListItem = explode('||', entitiesToUTF8(convertLegacyOptions($type_de_bacs_data)));
		$combo_type_de_bacs->ListData = $combo_type_de_bacs->ListItem;
	}else{
		$combo_type_de_bacs->ListItem = explode('||', entitiesToUTF8(convertLegacyOptions("D&#233;p&#244;t;;Fermentation;;Maturation;;Affinage")));
		$combo_type_de_bacs->ListData = $combo_type_de_bacs->ListItem;
	}
	$combo_type_de_bacs->SelectName = 'type_de_bacs';
	// combobox: niveau_de_remplissage
	$combo_niveau_de_remplissage = new Combo;
	$combo_niveau_de_remplissage->ListType = 0;
	$combo_niveau_de_remplissage->MultipleSeparator = ', ';
	$combo_niveau_de_remplissage->ListBoxHeight = 10;
	$combo_niveau_de_remplissage->RadiosPerLine = 1;
	if(is_file(dirname(__FILE__).'/hooks/bacs_du_site.niveau_de_remplissage.csv')) {
		$niveau_de_remplissage_data = addslashes(implode('', @file(dirname(__FILE__).'/hooks/bacs_du_site.niveau_de_remplissage.csv')));
		$combo_niveau_de_remplissage->ListItem = explode('||', entitiesToUTF8(convertLegacyOptions($niveau_de_remplissage_data)));
		$combo_niveau_de_remplissage->ListData = $combo_niveau_de_remplissage->ListItem;
	}else{
		$combo_niveau_de_remplissage->ListItem = explode('||', entitiesToUTF8(convertLegacyOptions("<25%;;Entre 25 % & 50 %;;Entre 50 % et 75 %;;> 75 %")));
		$combo_niveau_de_remplissage->ListData = $combo_niveau_de_remplissage->ListItem;
	}
	$combo_niveau_de_remplissage->SelectName = 'niveau_de_remplissage';

	if($selected_id) {
		// mm: check member permissions
		if(!$arrPerm[2]) {
			return "";
		}
		// mm: who is the owner?
		$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='bacs_du_site' and pkValue='".makeSafe($selected_id)."'");
		$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='bacs_du_site' and pkValue='".makeSafe($selected_id)."'");
		if($arrPerm[2]==1 && getLoggedMemberID()!=$ownerMemberID) {
			return "";
		}
		if($arrPerm[2]==2 && getLoggedGroupID()!=$ownerGroupID) {
			return "";
		}

		// can edit?
		if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3) {
			$AllowUpdate=1;
		}else{
			$AllowUpdate=0;
		}

		$res = sql("SELECT * FROM `bacs_du_site` WHERE `id`='" . makeSafe($selected_id) . "'", $eo);
		if(!($row = db_fetch_array($res))) {
			return error_message($Translation['No records found'], 'bacs_du_site_view.php', false);
		}
		$combo_appartient_site->SelectedData = $row['appartient_site'];
		$combo_type_de_bacs->SelectedData = $row['type_de_bacs'];
		$combo_niveau_de_remplissage->SelectedData = $row['niveau_de_remplissage'];
		$urow = $row; /* unsanitized data */
		$hc = new CI_Input();
		$row = $hc->xss_clean($row); /* sanitize data */
	} else {
		$combo_appartient_site->SelectedData = $filterer_appartient_site;
		$combo_type_de_bacs->SelectedText = ( $_REQUEST['FilterField'][1]=='3' && $_REQUEST['FilterOperator'][1]=='<=>' ? (get_magic_quotes_gpc() ? stripslashes($_REQUEST['FilterValue'][1]) : $_REQUEST['FilterValue'][1]) : "");
		$combo_niveau_de_remplissage->SelectedText = ( $_REQUEST['FilterField'][1]=='4' && $_REQUEST['FilterOperator'][1]=='<=>' ? (get_magic_quotes_gpc() ? stripslashes($_REQUEST['FilterValue'][1]) : $_REQUEST['FilterValue'][1]) : "");
	}
	$combo_appartient_site->HTML = '<span id="appartient_site-container' . $rnd1 . '"></span><input type="hidden" name="appartient_site" id="appartient_site' . $rnd1 . '" value="' . html_attr($combo_appartient_site->SelectedData) . '">';
	$combo_appartient_site->MatchText = '<span id="appartient_site-container-readonly' . $rnd1 . '"></span><input type="hidden" name="appartient_site" id="appartient_site' . $rnd1 . '" value="' . html_attr($combo_appartient_site->SelectedData) . '">';
	$combo_type_de_bacs->Render();
	$combo_niveau_de_remplissage->Render();

	ob_start();
	?>

	<script>
		// initial lookup values
		AppGini.current_appartient_site__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['appartient_site'] : $filterer_appartient_site); ?>"};

		jQuery(function() {
			setTimeout(function() {
				if(typeof(appartient_site_reload__RAND__) == 'function') appartient_site_reload__RAND__();
			}, 10); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
		function appartient_site_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#appartient_site-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_appartient_site__RAND__.value, t: 'bacs_du_site', f: 'appartient_site' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="appartient_site"]').val(resp.results[0].id);
							$j('[id=appartient_site-container-readonly__RAND__]').html('<span id="appartient_site-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=site_compostage_view_parent]').hide(); }else{ $j('.btn[id=site_compostage_view_parent]').show(); }


							if(typeof(appartient_site_update_autofills__RAND__) == 'function') appartient_site_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { /* */ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { /* */ return { s: term, p: page, t: 'bacs_du_site', f: 'appartient_site' }; },
					results: function(resp, page) { /* */ return resp; }
				},
				escapeMarkup: function(str) { /* */ return str; }
			}).on('change', function(e) {
				AppGini.current_appartient_site__RAND__.value = e.added.id;
				AppGini.current_appartient_site__RAND__.text = e.added.text;
				$j('[name="appartient_site"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=site_compostage_view_parent]').hide(); }else{ $j('.btn[id=site_compostage_view_parent]').show(); }


				if(typeof(appartient_site_update_autofills__RAND__) == 'function') appartient_site_update_autofills__RAND__();
			});

			if(!$j("#appartient_site-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_appartient_site__RAND__.value, t: 'bacs_du_site', f: 'appartient_site' },
					success: function(resp) {
						$j('[name="appartient_site"]').val(resp.results[0].id);
						$j('[id=appartient_site-container-readonly__RAND__]').html('<span id="appartient_site-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=site_compostage_view_parent]').hide(); }else{ $j('.btn[id=site_compostage_view_parent]').show(); }

						if(typeof(appartient_site_update_autofills__RAND__) == 'function') appartient_site_update_autofills__RAND__();
					}
				});
			}

		<?php }else{ ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_appartient_site__RAND__.value, t: 'bacs_du_site', f: 'appartient_site' },
				success: function(resp) {
					$j('[id=appartient_site-container__RAND__], [id=appartient_site-container-readonly__RAND__]').html('<span id="appartient_site-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=site_compostage_view_parent]').hide(); }else{ $j('.btn[id=site_compostage_view_parent]').show(); }

					if(typeof(appartient_site_update_autofills__RAND__) == 'function') appartient_site_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_contents());
	ob_end_clean();


	// code for template based detail view forms

	// open the detail view template
	if($dvprint) {
		$template_file = is_file("./{$TemplateDVP}") ? "./{$TemplateDVP}" : './templates/bacs_du_site_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	}else{
		$template_file = is_file("./{$TemplateDV}") ? "./{$TemplateDV}" : './templates/bacs_du_site_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Bacs du site details', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', ($_REQUEST['Embedded'] ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($AllowInsert) {
		if(!$selected_id) $templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return bacs_du_site_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return bacs_du_site_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	}else{
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if($_REQUEST['Embedded']) {
		$backAction = 'AppGini.closeParentModal(); return false;';
	}else{
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id) {
		if(!$_REQUEST['Embedded']) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$j(\'form\').eq(0).prop(\'novalidate\', true); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate) {
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return bacs_du_site_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		}else{
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3) { // allow delete?
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" onclick="return confirm(\'' . $Translation['are you sure?'] . '\');" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		}else{
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	}else{
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', ($ShowCancel ? '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>' : ''), $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$AllowInsert) || (!$selected_id && !$AllowInsert)) {
		$jsReadOnly .= "\tjQuery('#appartient_site').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#appartient_site_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#type_de_bacs').replaceWith('<div class=\"form-control-static\" id=\"type_de_bacs\">' + (jQuery('#type_de_bacs').val() || '') + '</div>'); jQuery('#type_de_bacs-multi-selection-help').hide();\n";
		$jsReadOnly .= "\tjQuery('#niveau_de_remplissage').replaceWith('<div class=\"form-control-static\" id=\"niveau_de_remplissage\">' + (jQuery('#niveau_de_remplissage').val() || '') + '</div>'); jQuery('#niveau_de_remplissage-multi-selection-help').hide();\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	}elseif($AllowInsert) {
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
			$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(appartient_site)%%>', $combo_appartient_site->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(appartient_site)%%>', $combo_appartient_site->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(appartient_site)%%>', urlencode($combo_appartient_site->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(type_de_bacs)%%>', $combo_type_de_bacs->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(type_de_bacs)%%>', $combo_type_de_bacs->SelectedData, $templateCode);
	$templateCode = str_replace('<%%COMBO(niveau_de_remplissage)%%>', $combo_niveau_de_remplissage->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(niveau_de_remplissage)%%>', $combo_niveau_de_remplissage->SelectedData, $templateCode);

	/* lookup fields array: 'lookup field name' => array('parent table name', 'lookup field caption') */
	$lookup_fields = array('appartient_site' => array('site_compostage', 'Appartient au site'), );
	foreach($lookup_fields as $luf => $ptfc) {
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']) {
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent hspacer-md" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] && !$_REQUEST['Embedded']) {
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-success add_new_parent hspacer-md" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus-sign"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(appartient_site)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(type_de_bacs)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(niveau_de_remplissage)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Commentaires)%%>', '', $templateCode);

	// process values
	if($selected_id) {
		if( $dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', safe_html($urow['id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', html_attr($row['id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode($urow['id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(appartient_site)%%>', safe_html($urow['appartient_site']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(appartient_site)%%>', html_attr($row['appartient_site']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(appartient_site)%%>', urlencode($urow['appartient_site']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(type_de_bacs)%%>', safe_html($urow['type_de_bacs']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(type_de_bacs)%%>', html_attr($row['type_de_bacs']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(type_de_bacs)%%>', urlencode($urow['type_de_bacs']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(niveau_de_remplissage)%%>', safe_html($urow['niveau_de_remplissage']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(niveau_de_remplissage)%%>', html_attr($row['niveau_de_remplissage']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(niveau_de_remplissage)%%>', urlencode($urow['niveau_de_remplissage']), $templateCode);
		if($AllowUpdate || $AllowInsert) {
			$templateCode = str_replace('<%%HTMLAREA(Commentaires)%%>', '<textarea name="Commentaires" id="Commentaires" rows="5">' . html_attr($row['Commentaires']) . '</textarea>', $templateCode);
		}else{
			$templateCode = str_replace('<%%HTMLAREA(Commentaires)%%>', '<div id="Commentaires" class="form-control-static">' . $row['Commentaires'] . '</div>', $templateCode);
		}
		$templateCode = str_replace('<%%VALUE(Commentaires)%%>', nl2br($row['Commentaires']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Commentaires)%%>', urlencode($urow['Commentaires']), $templateCode);
	}else{
		$templateCode = str_replace('<%%VALUE(id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(appartient_site)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(appartient_site)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(type_de_bacs)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(type_de_bacs)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(niveau_de_remplissage)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(niveau_de_remplissage)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%HTMLAREA(Commentaires)%%>', '<textarea name="Commentaires" id="Commentaires" rows="5"></textarea>', $templateCode);
	}

	// process translations
	foreach($Translation as $symbol=>$trans) {
		$templateCode = str_replace("<%%TRANSLATION($symbol)%%>", $trans, $templateCode);
	}

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if($_REQUEST['dvprint_x'] == '') {
		$templateCode .= "\n\n<script>\$j(function() {\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption) {
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id) {
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('bacs_du_site');
	if($selected_id) {
		$jdata = get_joined_record('bacs_du_site', $selected_id);
		if($jdata === false) $jdata = get_defaults('bacs_du_site');
		$rdata = $row;
	}
	$templateCode .= loadView('bacs_du_site-ajax-cache', array('rdata' => $rdata, 'jdata' => $jdata));

	// hook: bacs_du_site_dv
	if(function_exists('bacs_du_site_dv')) {
		$args=array();
		bacs_du_site_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}
?>