<?php

// Data functions (insert, update, delete, form) for table depots

// This script and data application were generated by AppGini 5.82
// Download AppGini for free from https://bigprof.com/appgini/download/

function depots_insert() {
	global $Translation;

	// mm: can member insert record?
	$arrPerm = getTablePermissions('depots');
	if(!$arrPerm[1]) return false;

	$data = array();
	$data['sur_le_site'] = $_REQUEST['sur_le_site'];
		if($data['sur_le_site'] == empty_lookup_value) { $data['sur_le_site'] = ''; }
	$data['dans_le_bac'] = $_REQUEST['dans_le_bac'];
		if($data['dans_le_bac'] == empty_lookup_value) { $data['dans_le_bac'] = ''; }
	$data['jour_heure'] = mysql_datetime($_REQUEST['jour_heure']);
		if($data['jour_heure'] == empty_lookup_value) { $data['jour_heure'] = ''; }
	$data['qte_vmh'] = $_REQUEST['qte_vmh'];
		if($data['qte_vmh'] == empty_lookup_value) { $data['qte_vmh'] = ''; }
	$data['qte_bds'] = $_REQUEST['qte_bds'];
		if($data['qte_bds'] == empty_lookup_value) { $data['qte_bds'] = ''; }
	$data['niveau_du_bac'] = $_REQUEST['niveau_du_bac'];
		if($data['niveau_du_bac'] == empty_lookup_value) { $data['niveau_du_bac'] = ''; }
	$data['cree_par'] = parseCode('<%%creatorUsername%%>', true);

	// hook: depots_before_insert
	if(function_exists('depots_before_insert')) {
		$args = array();
		if(!depots_before_insert($data, getMemberInfo(), $args)) { return false; }
	}

	$error = '';
	// set empty fields to NULL
	$data = array_map(function($v) { return ($v === '' ? NULL : $v); }, $data);
	insert('depots', backtick_keys_once($data), $error);
	if($error)
		die("{$error}<br><a href=\"#\" onclick=\"history.go(-1);\">{$Translation['< back']}</a>");

	$recID = db_insert_id(db_link());

	// automatic par_le_membre if passed as filterer
	if($_REQUEST['filterer_par_le_membre']) {
		sql("update `depots` set `par_le_membre`='" . makeSafe($_REQUEST['filterer_par_le_membre']) . "' where `id`='" . makeSafe($recID, false) . "'", $eo);
	}

	// hook: depots_after_insert
	if(function_exists('depots_after_insert')) {
		$res = sql("select * from `depots` where `id`='" . makeSafe($recID, false) . "' limit 1", $eo);
		if($row = db_fetch_assoc($res)) {
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args=array();
		if(!depots_after_insert($data, getMemberInfo(), $args)) { return $recID; }
	}

	// mm: save ownership data
	set_record_owner('depots', $recID, getLoggedMemberID());

	// if this record is a copy of another record, copy children if applicable
	if(!empty($_REQUEST['SelectedID'])) depots_copy_children($recID, $_REQUEST['SelectedID']);

	return $recID;
}

function depots_copy_children($destination_id, $source_id) {
	global $Translation;
	$requests = array(); // array of curl handlers for launching insert requests
	$eo = array('silentErrors' => true);
	$uploads_dir = realpath(dirname(__FILE__) . '/../' . $Translation['ImageFolder']);
	$safe_sid = makeSafe($source_id);

	// launch requests, asynchronously
	curl_batch($requests);
}

function depots_delete($selected_id, $AllowDeleteOfParents=false, $skipChecks=false) {
	// insure referential integrity ...
	global $Translation;
	$selected_id=makeSafe($selected_id);

	// mm: can member delete record?
	$arrPerm=getTablePermissions('depots');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='depots' and pkValue='$selected_id'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='depots' and pkValue='$selected_id'");
	if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3) { // allow delete?
		// delete allowed, so continue ...
	}else{
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: depots_before_delete
	if(function_exists('depots_before_delete')) {
		$args=array();
		if(!depots_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'];
	}

	sql("delete from `depots` where `id`='$selected_id'", $eo);

	// hook: depots_after_delete
	if(function_exists('depots_after_delete')) {
		$args=array();
		depots_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("delete from membership_userrecords where tableName='depots' and pkValue='$selected_id'", $eo);
}

function depots_update($selected_id) {
	global $Translation;

	// mm: can member edit record?
	$arrPerm=getTablePermissions('depots');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='depots' and pkValue='".makeSafe($selected_id)."'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='depots' and pkValue='".makeSafe($selected_id)."'");
	if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3) { // allow update?
		// update allowed, so continue ...
	}else{
		return false;
	}

	$data['sur_le_site'] = makeSafe($_REQUEST['sur_le_site']);
		if($data['sur_le_site'] == empty_lookup_value) { $data['sur_le_site'] = ''; }
	$data['dans_le_bac'] = makeSafe($_REQUEST['dans_le_bac']);
		if($data['dans_le_bac'] == empty_lookup_value) { $data['dans_le_bac'] = ''; }
	$data['jour_heure'] = mysql_datetime($_REQUEST['jour_heure']);
		if($data['jour_heure'] == empty_lookup_value) { $data['jour_heure'] = ''; }
	$data['qte_vmh'] = makeSafe($_REQUEST['qte_vmh']);
		if($data['qte_vmh'] == empty_lookup_value) { $data['qte_vmh'] = ''; }
	$data['qte_bds'] = makeSafe($_REQUEST['qte_bds']);
		if($data['qte_bds'] == empty_lookup_value) { $data['qte_bds'] = ''; }
	$data['niveau_du_bac'] = makeSafe($_REQUEST['niveau_du_bac']);
		if($data['niveau_du_bac'] == empty_lookup_value) { $data['niveau_du_bac'] = ''; }
	$data['date_maj'] = parseCode('<%%editingTimestamp%%>', false, true);
	$data['selectedID'] = makeSafe($selected_id);

	// hook: depots_before_update
	if(function_exists('depots_before_update')) {
		$args = array();
		if(!depots_before_update($data, getMemberInfo(), $args)) { return false; }
	}

	$o = array('silentErrors' => true);
	sql('update `depots` set       `sur_le_site`=' . (($data['sur_le_site'] !== '' && $data['sur_le_site'] !== NULL) ? "'{$data['sur_le_site']}'" : 'NULL') . ', `dans_le_bac`=' . (($data['dans_le_bac'] !== '' && $data['dans_le_bac'] !== NULL) ? "'{$data['dans_le_bac']}'" : 'NULL') . ', `jour_heure`=' . (($data['jour_heure'] !== '' && $data['jour_heure'] !== NULL) ? "'{$data['jour_heure']}'" : 'NULL') . ', `qte_vmh`=' . (($data['qte_vmh'] !== '' && $data['qte_vmh'] !== NULL) ? "'{$data['qte_vmh']}'" : 'NULL') . ', `qte_bds`=' . (($data['qte_bds'] !== '' && $data['qte_bds'] !== NULL) ? "'{$data['qte_bds']}'" : 'NULL') . ', `niveau_du_bac`=' . (($data['niveau_du_bac'] !== '' && $data['niveau_du_bac'] !== NULL) ? "'{$data['niveau_du_bac']}'" : 'NULL') . ', `date_maj`=' . "'{$data['date_maj']}'" . " where `id`='".makeSafe($selected_id)."'", $o);
	if($o['error']!='') {
		echo $o['error'];
		echo '<a href="depots_view.php?SelectedID='.urlencode($selected_id)."\">{$Translation['< back']}</a>";
		exit;
	}


	// hook: depots_after_update
	if(function_exists('depots_after_update')) {
		$res = sql("SELECT * FROM `depots` WHERE `id`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) {
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = $data['id'];
		$args = array();
		if(!depots_after_update($data, getMemberInfo(), $args)) { return; }
	}

	// mm: update ownership data
	sql("update `membership_userrecords` set `dateUpdated`='" . time() . "' where `tableName`='depots' and `pkValue`='" . makeSafe($selected_id) . "'", $eo);

}

function depots_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $ShowCancel = 0, $TemplateDV = '', $TemplateDVP = '') {
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;

	// mm: get table permissions
	$arrPerm=getTablePermissions('depots');
	if(!$arrPerm[1] && $selected_id=='') { return ''; }
	$AllowInsert = ($arrPerm[1] ? true : false);
	// print preview?
	$dvprint = false;
	if($selected_id && $_REQUEST['dvprint_x'] != '') {
		$dvprint = true;
	}

	$filterer_sur_le_site = thisOr(undo_magic_quotes($_REQUEST['filterer_sur_le_site']), '');
	$filterer_par_le_membre = thisOr(undo_magic_quotes($_REQUEST['filterer_par_le_membre']), '');
	$filterer_dans_le_bac = thisOr(undo_magic_quotes($_REQUEST['filterer_dans_le_bac']), '');

	// populate filterers, starting from children to grand-parents
	if($filterer_dans_le_bac && !$filterer_sur_le_site) $filterer_sur_le_site = sqlValue("select appartient_site from bacs_du_site where id='" . makeSafe($filterer_dans_le_bac) . "'");

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: sur_le_site
	$combo_sur_le_site = new DataCombo;
	// combobox: par_le_membre
	$combo_par_le_membre = new DataCombo;
	// combobox: dans_le_bac, filterable by: sur_le_site
	$combo_dans_le_bac = new DataCombo;
	// combobox: niveau_du_bac
	$combo_niveau_du_bac = new Combo;
	$combo_niveau_du_bac->ListType = 0;
	$combo_niveau_du_bac->MultipleSeparator = ', ';
	$combo_niveau_du_bac->ListBoxHeight = 10;
	$combo_niveau_du_bac->RadiosPerLine = 1;
	if(is_file(dirname(__FILE__).'/hooks/depots.niveau_du_bac.csv')) {
		$niveau_du_bac_data = addslashes(implode('', @file(dirname(__FILE__).'/hooks/depots.niveau_du_bac.csv')));
		$combo_niveau_du_bac->ListItem = explode('||', entitiesToUTF8(convertLegacyOptions($niveau_du_bac_data)));
		$combo_niveau_du_bac->ListData = $combo_niveau_du_bac->ListItem;
	}else{
		$combo_niveau_du_bac->ListItem = explode('||', entitiesToUTF8(convertLegacyOptions("Moins de 25%;;Entre 25 % & 50 %;;Entre 50 % et 75 %;;\> 75 %")));
		$combo_niveau_du_bac->ListData = $combo_niveau_du_bac->ListItem;
	}
	$combo_niveau_du_bac->SelectName = 'niveau_du_bac';

	if($selected_id) {
		// mm: check member permissions
		if(!$arrPerm[2]) {
			return "";
		}
		// mm: who is the owner?
		$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='depots' and pkValue='".makeSafe($selected_id)."'");
		$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='depots' and pkValue='".makeSafe($selected_id)."'");
		if($arrPerm[2]==1 && getLoggedMemberID()!=$ownerMemberID) {
			return "";
		}
		if($arrPerm[2]==2 && getLoggedGroupID()!=$ownerGroupID) {
			return "";
		}

		// can edit?
		if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3) {
			$AllowUpdate=1;
		}else{
			$AllowUpdate=0;
		}

		$res = sql("SELECT * FROM `depots` WHERE `id`='" . makeSafe($selected_id) . "'", $eo);
		if(!($row = db_fetch_array($res))) {
			return error_message($Translation['No records found'], 'depots_view.php', false);
		}
		$combo_sur_le_site->SelectedData = $row['sur_le_site'];
		$combo_par_le_membre->SelectedData = $row['par_le_membre'];
		$combo_dans_le_bac->SelectedData = $row['dans_le_bac'];
		$combo_niveau_du_bac->SelectedData = $row['niveau_du_bac'];
		$urow = $row; /* unsanitized data */
		$hc = new CI_Input();
		$row = $hc->xss_clean($row); /* sanitize data */
	} else {
		$combo_sur_le_site->SelectedData = $filterer_sur_le_site;
		$combo_par_le_membre->SelectedData = $filterer_par_le_membre;
		$combo_dans_le_bac->SelectedData = $filterer_dans_le_bac;
		$combo_niveau_du_bac->SelectedText = ( $_REQUEST['FilterField'][1]=='8' && $_REQUEST['FilterOperator'][1]=='<=>' ? (get_magic_quotes_gpc() ? stripslashes($_REQUEST['FilterValue'][1]) : $_REQUEST['FilterValue'][1]) : "");
	}
	$combo_sur_le_site->HTML = '<span id="sur_le_site-container' . $rnd1 . '"></span><input type="hidden" name="sur_le_site" id="sur_le_site' . $rnd1 . '" value="' . html_attr($combo_sur_le_site->SelectedData) . '">';
	$combo_sur_le_site->MatchText = '<span id="sur_le_site-container-readonly' . $rnd1 . '"></span><input type="hidden" name="sur_le_site" id="sur_le_site' . $rnd1 . '" value="' . html_attr($combo_sur_le_site->SelectedData) . '">';
	$combo_par_le_membre->HTML = '<span id="par_le_membre-container' . $rnd1 . '"></span><input type="hidden" name="par_le_membre" id="par_le_membre' . $rnd1 . '" value="' . html_attr($combo_par_le_membre->SelectedData) . '">';
	$combo_par_le_membre->MatchText = '<span id="par_le_membre-container-readonly' . $rnd1 . '"></span><input type="hidden" name="par_le_membre" id="par_le_membre' . $rnd1 . '" value="' . html_attr($combo_par_le_membre->SelectedData) . '">';
	$combo_dans_le_bac->HTML = '<span id="dans_le_bac-container' . $rnd1 . '"></span><input type="hidden" name="dans_le_bac" id="dans_le_bac' . $rnd1 . '" value="' . html_attr($combo_dans_le_bac->SelectedData) . '">';
	$combo_dans_le_bac->MatchText = '<span id="dans_le_bac-container-readonly' . $rnd1 . '"></span><input type="hidden" name="dans_le_bac" id="dans_le_bac' . $rnd1 . '" value="' . html_attr($combo_dans_le_bac->SelectedData) . '">';
	$combo_niveau_du_bac->Render();

	ob_start();
	?>

	<script>
		// initial lookup values
		AppGini.current_sur_le_site__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['sur_le_site'] : $filterer_sur_le_site); ?>"};
		AppGini.current_par_le_membre__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['par_le_membre'] : $filterer_par_le_membre); ?>"};
		AppGini.current_dans_le_bac__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['dans_le_bac'] : $filterer_dans_le_bac); ?>"};

		jQuery(function() {
			setTimeout(function() {
				if(typeof(sur_le_site_reload__RAND__) == 'function') sur_le_site_reload__RAND__();
				if(typeof(par_le_membre_reload__RAND__) == 'function') par_le_membre_reload__RAND__();
				<?php echo (!$AllowUpdate || $dvprint ? 'if(typeof(dans_le_bac_reload__RAND__) == \'function\') dans_le_bac_reload__RAND__(AppGini.current_sur_le_site__RAND__.value);' : ''); ?>
			}, 10); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
		function sur_le_site_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#sur_le_site-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_sur_le_site__RAND__.value, t: 'depots', f: 'sur_le_site' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="sur_le_site"]').val(resp.results[0].id);
							$j('[id=sur_le_site-container-readonly__RAND__]').html('<span id="sur_le_site-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=site_compostage_view_parent]').hide(); }else{ $j('.btn[id=site_compostage_view_parent]').show(); }

						if(typeof(dans_le_bac_reload__RAND__) == 'function') dans_le_bac_reload__RAND__(AppGini.current_sur_le_site__RAND__.value);

							if(typeof(sur_le_site_update_autofills__RAND__) == 'function') sur_le_site_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { /* */ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { /* */ return { s: term, p: page, t: 'depots', f: 'sur_le_site' }; },
					results: function(resp, page) { /* */ return resp; }
				},
				escapeMarkup: function(str) { /* */ return str; }
			}).on('change', function(e) {
				AppGini.current_sur_le_site__RAND__.value = e.added.id;
				AppGini.current_sur_le_site__RAND__.text = e.added.text;
				$j('[name="sur_le_site"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=site_compostage_view_parent]').hide(); }else{ $j('.btn[id=site_compostage_view_parent]').show(); }

						if(typeof(dans_le_bac_reload__RAND__) == 'function') dans_le_bac_reload__RAND__(AppGini.current_sur_le_site__RAND__.value);

				if(typeof(sur_le_site_update_autofills__RAND__) == 'function') sur_le_site_update_autofills__RAND__();
			});

			if(!$j("#sur_le_site-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_sur_le_site__RAND__.value, t: 'depots', f: 'sur_le_site' },
					success: function(resp) {
						$j('[name="sur_le_site"]').val(resp.results[0].id);
						$j('[id=sur_le_site-container-readonly__RAND__]').html('<span id="sur_le_site-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=site_compostage_view_parent]').hide(); }else{ $j('.btn[id=site_compostage_view_parent]').show(); }

						if(typeof(sur_le_site_update_autofills__RAND__) == 'function') sur_le_site_update_autofills__RAND__();
					}
				});
			}

		<?php }else{ ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_sur_le_site__RAND__.value, t: 'depots', f: 'sur_le_site' },
				success: function(resp) {
					$j('[id=sur_le_site-container__RAND__], [id=sur_le_site-container-readonly__RAND__]').html('<span id="sur_le_site-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=site_compostage_view_parent]').hide(); }else{ $j('.btn[id=site_compostage_view_parent]').show(); }

					if(typeof(sur_le_site_update_autofills__RAND__) == 'function') sur_le_site_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function par_le_membre_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#par_le_membre-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_par_le_membre__RAND__.value, t: 'depots', f: 'par_le_membre' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="par_le_membre"]').val(resp.results[0].id);
							$j('[id=par_le_membre-container-readonly__RAND__]').html('<span id="par_le_membre-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=membres_view_parent]').hide(); }else{ $j('.btn[id=membres_view_parent]').show(); }


							if(typeof(par_le_membre_update_autofills__RAND__) == 'function') par_le_membre_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { /* */ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { /* */ return { s: term, p: page, t: 'depots', f: 'par_le_membre' }; },
					results: function(resp, page) { /* */ return resp; }
				},
				escapeMarkup: function(str) { /* */ return str; }
			}).on('change', function(e) {
				AppGini.current_par_le_membre__RAND__.value = e.added.id;
				AppGini.current_par_le_membre__RAND__.text = e.added.text;
				$j('[name="par_le_membre"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=membres_view_parent]').hide(); }else{ $j('.btn[id=membres_view_parent]').show(); }


				if(typeof(par_le_membre_update_autofills__RAND__) == 'function') par_le_membre_update_autofills__RAND__();
			});

			if(!$j("#par_le_membre-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_par_le_membre__RAND__.value, t: 'depots', f: 'par_le_membre' },
					success: function(resp) {
						$j('[name="par_le_membre"]').val(resp.results[0].id);
						$j('[id=par_le_membre-container-readonly__RAND__]').html('<span id="par_le_membre-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=membres_view_parent]').hide(); }else{ $j('.btn[id=membres_view_parent]').show(); }

						if(typeof(par_le_membre_update_autofills__RAND__) == 'function') par_le_membre_update_autofills__RAND__();
					}
				});
			}

		<?php }else{ ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_par_le_membre__RAND__.value, t: 'depots', f: 'par_le_membre' },
				success: function(resp) {
					$j('[id=par_le_membre-container__RAND__], [id=par_le_membre-container-readonly__RAND__]').html('<span id="par_le_membre-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=membres_view_parent]').hide(); }else{ $j('.btn[id=membres_view_parent]').show(); }

					if(typeof(par_le_membre_update_autofills__RAND__) == 'function') par_le_membre_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function dans_le_bac_reload__RAND__(filterer_sur_le_site) {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#dans_le_bac-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { filterer_sur_le_site: filterer_sur_le_site, id: AppGini.current_dans_le_bac__RAND__.value, t: 'depots', f: 'dans_le_bac' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="dans_le_bac"]').val(resp.results[0].id);
							$j('[id=dans_le_bac-container-readonly__RAND__]').html('<span id="dans_le_bac-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=bacs_du_site_view_parent]').hide(); }else{ $j('.btn[id=bacs_du_site_view_parent]').show(); }


							if(typeof(dans_le_bac_update_autofills__RAND__) == 'function') dans_le_bac_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { /* */ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { /* */ return { filterer_sur_le_site: filterer_sur_le_site, s: term, p: page, t: 'depots', f: 'dans_le_bac' }; },
					results: function(resp, page) { /* */ return resp; }
				},
				escapeMarkup: function(str) { /* */ return str; }
			}).on('change', function(e) {
				AppGini.current_dans_le_bac__RAND__.value = e.added.id;
				AppGini.current_dans_le_bac__RAND__.text = e.added.text;
				$j('[name="dans_le_bac"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=bacs_du_site_view_parent]').hide(); }else{ $j('.btn[id=bacs_du_site_view_parent]').show(); }


				if(typeof(dans_le_bac_update_autofills__RAND__) == 'function') dans_le_bac_update_autofills__RAND__();
			});

			if(!$j("#dans_le_bac-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_dans_le_bac__RAND__.value, t: 'depots', f: 'dans_le_bac' },
					success: function(resp) {
						$j('[name="dans_le_bac"]').val(resp.results[0].id);
						$j('[id=dans_le_bac-container-readonly__RAND__]').html('<span id="dans_le_bac-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=bacs_du_site_view_parent]').hide(); }else{ $j('.btn[id=bacs_du_site_view_parent]').show(); }

						if(typeof(dans_le_bac_update_autofills__RAND__) == 'function') dans_le_bac_update_autofills__RAND__();
					}
				});
			}

		<?php }else{ ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_dans_le_bac__RAND__.value, t: 'depots', f: 'dans_le_bac' },
				success: function(resp) {
					$j('[id=dans_le_bac-container__RAND__], [id=dans_le_bac-container-readonly__RAND__]').html('<span id="dans_le_bac-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=bacs_du_site_view_parent]').hide(); }else{ $j('.btn[id=bacs_du_site_view_parent]').show(); }

					if(typeof(dans_le_bac_update_autofills__RAND__) == 'function') dans_le_bac_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_contents());
	ob_end_clean();


	// code for template based detail view forms

	// open the detail view template
	if($dvprint) {
		$template_file = is_file("./{$TemplateDVP}") ? "./{$TemplateDVP}" : './templates/depots_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	}else{
		$template_file = is_file("./{$TemplateDV}") ? "./{$TemplateDV}" : './templates/depots_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Depot details', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', ($_REQUEST['Embedded'] ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($AllowInsert) {
		if(!$selected_id) $templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return depots_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return depots_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	}else{
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if($_REQUEST['Embedded']) {
		$backAction = 'AppGini.closeParentModal(); return false;';
	}else{
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id) {
		if(!$_REQUEST['Embedded']) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$j(\'form\').eq(0).prop(\'novalidate\', true); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate) {
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return depots_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		}else{
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3) { // allow delete?
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" onclick="return confirm(\'' . $Translation['are you sure?'] . '\');" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		}else{
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	}else{
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', ($ShowCancel ? '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>' : ''), $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$AllowInsert) || (!$selected_id && !$AllowInsert)) {
		$jsReadOnly .= "\tjQuery('#sur_le_site').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#sur_le_site_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#dans_le_bac').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#dans_le_bac_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#jour_heure').parents('.input-group').replaceWith('<div class=\"form-control-static\" id=\"jour_heure\">' + (jQuery('#jour_heure').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#qte_vmh').replaceWith('<div class=\"form-control-static\" id=\"qte_vmh\">' + (jQuery('#qte_vmh').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#qte_bds').replaceWith('<div class=\"form-control-static\" id=\"qte_bds\">' + (jQuery('#qte_bds').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#niveau_du_bac').replaceWith('<div class=\"form-control-static\" id=\"niveau_du_bac\">' + (jQuery('#niveau_du_bac').val() || '') + '</div>'); jQuery('#niveau_du_bac-multi-selection-help').hide();\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	}elseif($AllowInsert) {
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
		$locale = isset($Translation['datetimepicker locale']) ? ", locale: '{$Translation['datetimepicker locale']}'" : '';
		$jsEditable .= "\tjQuery('#jour_heure').addClass('always_shown').parents('.input-group').datetimepicker({ toolbarPlacement: 'top', sideBySide: true, showClear: true, showTodayButton: true, showClose: true, icons: { close: 'glyphicon glyphicon-ok' }, format: AppGini.datetimeFormat('dt') {$locale} });";
			$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(sur_le_site)%%>', $combo_sur_le_site->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(sur_le_site)%%>', $combo_sur_le_site->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(sur_le_site)%%>', urlencode($combo_sur_le_site->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(par_le_membre)%%>', $combo_par_le_membre->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(par_le_membre)%%>', $combo_par_le_membre->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(par_le_membre)%%>', urlencode($combo_par_le_membre->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(dans_le_bac)%%>', $combo_dans_le_bac->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(dans_le_bac)%%>', $combo_dans_le_bac->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(dans_le_bac)%%>', urlencode($combo_dans_le_bac->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(niveau_du_bac)%%>', $combo_niveau_du_bac->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(niveau_du_bac)%%>', $combo_niveau_du_bac->SelectedData, $templateCode);

	/* lookup fields array: 'lookup field name' => array('parent table name', 'lookup field caption') */
	$lookup_fields = array('sur_le_site' => array('site_compostage', 'Sur le site'), 'par_le_membre' => array('membres', 'Par le membre'), 'dans_le_bac' => array('bacs_du_site', 'Dans le bac'), );
	foreach($lookup_fields as $luf => $ptfc) {
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']) {
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent hspacer-md" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] && !$_REQUEST['Embedded']) {
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-success add_new_parent hspacer-md" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus-sign"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(sur_le_site)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(par_le_membre)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(dans_le_bac)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(jour_heure)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(qte_vmh)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(qte_bds)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(niveau_du_bac)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(cree_par)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(date_maj)%%>', '', $templateCode);

	// process values
	if($selected_id) {
		if( $dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', safe_html($urow['id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', html_attr($row['id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode($urow['id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(sur_le_site)%%>', safe_html($urow['sur_le_site']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(sur_le_site)%%>', html_attr($row['sur_le_site']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(sur_le_site)%%>', urlencode($urow['sur_le_site']), $templateCode);
		$templateCode = str_replace('<%%VALUE(par_le_membre)%%>', safe_html($urow['par_le_membre']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(par_le_membre)%%>', urlencode($urow['par_le_membre']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(dans_le_bac)%%>', safe_html($urow['dans_le_bac']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(dans_le_bac)%%>', html_attr($row['dans_le_bac']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(dans_le_bac)%%>', urlencode($urow['dans_le_bac']), $templateCode);
		$templateCode = str_replace('<%%VALUE(jour_heure)%%>', app_datetime($row['jour_heure'], 'dt'), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(jour_heure)%%>', urlencode(app_datetime($urow['jour_heure'], 'dt')), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(qte_vmh)%%>', safe_html($urow['qte_vmh']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(qte_vmh)%%>', html_attr($row['qte_vmh']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(qte_vmh)%%>', urlencode($urow['qte_vmh']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(qte_bds)%%>', safe_html($urow['qte_bds']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(qte_bds)%%>', html_attr($row['qte_bds']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(qte_bds)%%>', urlencode($urow['qte_bds']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(niveau_du_bac)%%>', safe_html($urow['niveau_du_bac']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(niveau_du_bac)%%>', html_attr($row['niveau_du_bac']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(niveau_du_bac)%%>', urlencode($urow['niveau_du_bac']), $templateCode);
		$templateCode = str_replace('<%%VALUE(cree_par)%%>', safe_html($urow['cree_par']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(cree_par)%%>', urlencode($urow['cree_par']), $templateCode);
		$templateCode = str_replace('<%%VALUE(date_maj)%%>', safe_html($urow['date_maj']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(date_maj)%%>', urlencode($urow['date_maj']), $templateCode);
	}else{
		$templateCode = str_replace('<%%VALUE(id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(sur_le_site)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(sur_le_site)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(par_le_membre)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(par_le_membre)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(dans_le_bac)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(dans_le_bac)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(jour_heure)%%>', '<%%creationDateTime%%>', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(jour_heure)%%>', urlencode('<%%creationDateTime%%>'), $templateCode);
		$templateCode = str_replace('<%%VALUE(qte_vmh)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(qte_vmh)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(qte_bds)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(qte_bds)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(niveau_du_bac)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(niveau_du_bac)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(cree_par)%%>', '<%%creatorUsername%%>', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(cree_par)%%>', urlencode('<%%creatorUsername%%>'), $templateCode);
		$templateCode = str_replace('<%%VALUE(date_maj)%%>', '<%%editingTimestamp%%>', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(date_maj)%%>', urlencode('<%%editingTimestamp%%>'), $templateCode);
	}

	// process translations
	foreach($Translation as $symbol=>$trans) {
		$templateCode = str_replace("<%%TRANSLATION($symbol)%%>", $trans, $templateCode);
	}

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if($_REQUEST['dvprint_x'] == '') {
		$templateCode .= "\n\n<script>\$j(function() {\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption) {
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id) {
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields
	if( $_REQUEST['FilterField'][1]=='3' && $_REQUEST['FilterOperator'][1]=='<=>') {
		$templateCode.="\n<input type=hidden name=par_le_membre value=\"" . html_attr((get_magic_quotes_gpc() ? stripslashes($_REQUEST['FilterValue'][1]) : $_REQUEST['FilterValue'][1]))."\">\n";
	}

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('depots');
	if($selected_id) {
		$jdata = get_joined_record('depots', $selected_id);
		if($jdata === false) $jdata = get_defaults('depots');
		$rdata = $row;
	}
	$templateCode .= loadView('depots-ajax-cache', array('rdata' => $rdata, 'jdata' => $jdata));

	// hook: depots_dv
	if(function_exists('depots_dv')) {
		$args=array();
		depots_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}
?>