<?php
// This script and data application were generated by AppGini 5.82
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/depots.php");
	include("$currDir/depots_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('depots');
	if(!$perm[0]) {
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "depots";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = array(
		"`depots`.`id`" => "id",
		"IF(    CHAR_LENGTH(`site_compostage1`.`nom_du_site`), CONCAT_WS('',   `site_compostage1`.`nom_du_site`, ' '), '') /* Sur le site */" => "sur_le_site",
		"IF(    CHAR_LENGTH(`membres1`.`prenom`) || CHAR_LENGTH(`membres1`.`Nom`), CONCAT_WS('',   `membres1`.`prenom`, `membres1`.`Nom`), '') /* Par le membre */" => "par_le_membre",
		"IF(    CHAR_LENGTH(`bacs_du_site1`.`type_de_bacs`) || CHAR_LENGTH(`site_compostage2`.`nom_du_site`), CONCAT_WS('',   `bacs_du_site1`.`type_de_bacs`, ' du site ', `site_compostage2`.`nom_du_site`), '') /* Dans le bac */" => "dans_le_bac",
		"DATE_FORMAT(`depots`.`jour_heure`, '%Y/%m/%d')" => "jour_heure",
		"`depots`.`qte_vmh`" => "qte_vmh",
		"`depots`.`qte_bds`" => "qte_bds",
		"`depots`.`niveau_du_bac`" => "niveau_du_bac",
		"`depots`.`cree_par`" => "cree_par",
		"`depots`.`date_maj`" => "date_maj",
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(
		1 => '`depots`.`id`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => '`depots`.`jour_heure`',
		6 => '`depots`.`qte_vmh`',
		7 => '`depots`.`qte_bds`',
		8 => 8,
		9 => 9,
		10 => '`depots`.`date_maj`',
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = array(
		"`depots`.`id`" => "id",
		"IF(    CHAR_LENGTH(`site_compostage1`.`nom_du_site`), CONCAT_WS('',   `site_compostage1`.`nom_du_site`, ' '), '') /* Sur le site */" => "sur_le_site",
		"IF(    CHAR_LENGTH(`membres1`.`prenom`) || CHAR_LENGTH(`membres1`.`Nom`), CONCAT_WS('',   `membres1`.`prenom`, `membres1`.`Nom`), '') /* Par le membre */" => "par_le_membre",
		"IF(    CHAR_LENGTH(`bacs_du_site1`.`type_de_bacs`) || CHAR_LENGTH(`site_compostage2`.`nom_du_site`), CONCAT_WS('',   `bacs_du_site1`.`type_de_bacs`, ' du site ', `site_compostage2`.`nom_du_site`), '') /* Dans le bac */" => "dans_le_bac",
		"DATE_FORMAT(`depots`.`jour_heure`, '%Y/%m/%d')" => "jour_heure",
		"`depots`.`qte_vmh`" => "qte_vmh",
		"`depots`.`qte_bds`" => "qte_bds",
		"`depots`.`niveau_du_bac`" => "niveau_du_bac",
		"`depots`.`cree_par`" => "cree_par",
		"`depots`.`date_maj`" => "date_maj",
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters = array(
		"`depots`.`id`" => "ID",
		"IF(    CHAR_LENGTH(`site_compostage1`.`nom_du_site`), CONCAT_WS('',   `site_compostage1`.`nom_du_site`, ' '), '') /* Sur le site */" => "Sur le site",
		"IF(    CHAR_LENGTH(`membres1`.`prenom`) || CHAR_LENGTH(`membres1`.`Nom`), CONCAT_WS('',   `membres1`.`prenom`, `membres1`.`Nom`), '') /* Par le membre */" => "Par le membre",
		"IF(    CHAR_LENGTH(`bacs_du_site1`.`type_de_bacs`) || CHAR_LENGTH(`site_compostage2`.`nom_du_site`), CONCAT_WS('',   `bacs_du_site1`.`type_de_bacs`, ' du site ', `site_compostage2`.`nom_du_site`), '') /* Dans le bac */" => "Dans le bac",
		"`depots`.`jour_heure`" => "Jour & heure du d&#233;p&#244;t",
		"`depots`.`qte_vmh`" => "Qte vmh",
		"`depots`.`qte_bds`" => "Qte bds",
		"`depots`.`niveau_du_bac`" => "Niveau du bac",
		"`depots`.`cree_par`" => "Cree par",
		"`depots`.`date_maj`" => "Date maj",
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS = array(
		"`depots`.`id`" => "id",
		"IF(    CHAR_LENGTH(`site_compostage1`.`nom_du_site`), CONCAT_WS('',   `site_compostage1`.`nom_du_site`, ' '), '') /* Sur le site */" => "sur_le_site",
		"IF(    CHAR_LENGTH(`membres1`.`prenom`) || CHAR_LENGTH(`membres1`.`Nom`), CONCAT_WS('',   `membres1`.`prenom`, `membres1`.`Nom`), '') /* Par le membre */" => "par_le_membre",
		"IF(    CHAR_LENGTH(`bacs_du_site1`.`type_de_bacs`) || CHAR_LENGTH(`site_compostage2`.`nom_du_site`), CONCAT_WS('',   `bacs_du_site1`.`type_de_bacs`, ' du site ', `site_compostage2`.`nom_du_site`), '') /* Dans le bac */" => "dans_le_bac",
		"DATE_FORMAT(`depots`.`jour_heure`, '%Y/%m/%d')" => "jour_heure",
		"`depots`.`qte_vmh`" => "qte_vmh",
		"`depots`.`qte_bds`" => "qte_bds",
		"`depots`.`niveau_du_bac`" => "niveau_du_bac",
		"`depots`.`cree_par`" => "cree_par",
		"`depots`.`date_maj`" => "date_maj",
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array('sur_le_site' => 'Sur le site', 'par_le_membre' => 'Par le membre', 'dans_le_bac' => 'Dans le bac', );

	$x->QueryFrom = "`depots` LEFT JOIN `site_compostage` as site_compostage1 ON `site_compostage1`.`id`=`depots`.`sur_le_site` LEFT JOIN `membres` as membres1 ON `membres1`.`id`=`depots`.`par_le_membre` LEFT JOIN `bacs_du_site` as bacs_du_site1 ON `bacs_du_site1`.`id`=`depots`.`dans_le_bac` LEFT JOIN `site_compostage` as site_compostage2 ON `site_compostage2`.`id`=`bacs_du_site1`.`appartient_site` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = false;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "depots_view.php";
	$x->RedirectAfterInsert = "depots_view.php?SelectedID=#ID#";
	$x->TableTitle = "D&#233;p&#244;ts";
	$x->TableIcon = "resources/table_icons/light_circle_green.png";
	$x->PrimaryKey = "`depots`.`id`";

	$x->ColWidth   = array(  150, 150, 150, 150, 150, 150);
	$x->ColCaption = array("Sur le site", "Dans le bac", "Jour & heure du d&#233;p&#244;t", "Qte vmh", "Qte bds", "Niveau du bac");
	$x->ColFieldName = array('sur_le_site', 'dans_le_bac', 'jour_heure', 'qte_vmh', 'qte_bds', 'niveau_du_bac');
	$x->ColNumber  = array(2, 4, 5, 6, 7, 8);

	// template paths below are based on the app main directory
	$x->Template = 'templates/depots_templateTV.html';
	$x->SelectedTemplate = 'templates/depots_templateTVS.html';
	$x->TemplateDV = 'templates/depots_templateDV.html';
	$x->TemplateDVP = 'templates/depots_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HighlightColor = '#FFF0C2';
	$x->HasCalculatedFields = false;

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))) { $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])) { // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `depots`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='depots' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])) { // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `depots`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='depots' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3) { // view all
		// no further action
	}elseif($perm[2]==0) { // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`depots`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: depots_init
	$render=TRUE;
	if(function_exists('depots_init')) {
		$args=array();
		$render=depots_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// column sums
	if(strpos($x->HTML, '<!-- tv data below -->')) {
		// if printing multi-selection TV, calculate the sum only for the selected records
		if(isset($_REQUEST['Print_x']) && is_array($_REQUEST['record_selector'])) {
			$QueryWhere = '';
			foreach($_REQUEST['record_selector'] as $id) {   // get selected records
				if($id != '') $QueryWhere .= "'" . makeSafe($id) . "',";
			}
			if($QueryWhere != '') {
				$QueryWhere = 'where `depots`.`id` in ('.substr($QueryWhere, 0, -1).')';
			}else{ // if no selected records, write the where clause to return an empty result
				$QueryWhere = 'where 1=0';
			}
		}else{
			$QueryWhere = $x->QueryWhere;
		}

		$sumQuery = "select sum(`depots`.`qte_vmh`), sum(`depots`.`qte_bds`) from {$x->QueryFrom} {$QueryWhere}";
		$res = sql($sumQuery, $eo);
		if($row = db_fetch_row($res)) {
			$sumRow = '<tr class="success">';
			if(!isset($_REQUEST['Print_x'])) $sumRow .= '<td class="text-center"><strong>&sum;</strong></td>';
			$sumRow .= '<td class="depots-sur_le_site"></td>';
			$sumRow .= '<td class="depots-dans_le_bac"></td>';
			$sumRow .= '<td class="depots-jour_heure"></td>';
			$sumRow .= "<td class=\"depots-qte_vmh text-right\">{$row[0]}</td>";
			$sumRow .= "<td class=\"depots-qte_bds text-right\">{$row[1]}</td>";
			$sumRow .= '<td class="depots-niveau_du_bac"></td>';
			$sumRow .= '</tr>';

			$x->HTML = str_replace('<!-- tv data below -->', '', $x->HTML);
			$x->HTML = str_replace('<!-- tv data above -->', $sumRow, $x->HTML);
		}
	}

	// hook: depots_header
	$headerCode='';
	if(function_exists('depots_header')) {
		$args=array();
		$headerCode=depots_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode) {
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: depots_footer
	$footerCode='';
	if(function_exists('depots_footer')) {
		$args=array();
		$footerCode=depots_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode) {
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>