<?php
// This script and data application were generated by AppGini 5.82
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/intervention.php");
	include("$currDir/intervention_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('intervention');
	if(!$perm[0]) {
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "intervention";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = array(
		"`intervention`.`id`" => "id",
		"IF(    CHAR_LENGTH(`membres1`.`Nom`) || CHAR_LENGTH(`membres1`.`prenom`), CONCAT_WS('',   `membres1`.`Nom`, `membres1`.`prenom`), '') /* Demande par */" => "demande_par",
		"DATE_FORMAT(`intervention`.`date_demande`, '%Y/%m/%d')" => "date_demande",
		"IF(    CHAR_LENGTH(`membres2`.`Nom`) || CHAR_LENGTH(`membres2`.`prenom`), CONCAT_WS('',   `membres2`.`Nom`, `membres2`.`prenom`), '') /* Realise par */" => "realise_par",
		"DATE_FORMAT(`intervention`.`date_realisation`, '%Y/%m/%d')" => "date_realisation",
		"IF(    CHAR_LENGTH(`site_compostage1`.`nom_du_site`), CONCAT_WS('',   `site_compostage1`.`nom_du_site`), '') /* Pour site */" => "pour_site",
		"IF(    CHAR_LENGTH(`bacs_du_site1`.`type_de_bacs`) || CHAR_LENGTH(`site_compostage2`.`nom_du_site`), CONCAT_WS('',   `bacs_du_site1`.`type_de_bacs`, ' du site ', `site_compostage2`.`nom_du_site`), '') /* Pour bac */" => "pour_bac",
		"`intervention`.`type_intervention`" => "type_intervention",
		"`intervention`.`statut_intervention`" => "statut_intervention",
		"`intervention`.`description`" => "description",
		"`intervention`.`cree_par`" => "cree_par",
		"`intervention`.`date_maj`" => "date_maj",
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(
		1 => '`intervention`.`id`',
		2 => 2,
		3 => '`intervention`.`date_demande`',
		4 => 4,
		5 => '`intervention`.`date_realisation`',
		6 => '`site_compostage1`.`nom_du_site`',
		7 => 7,
		8 => 8,
		9 => 9,
		10 => 10,
		11 => 11,
		12 => '`intervention`.`date_maj`',
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = array(
		"`intervention`.`id`" => "id",
		"IF(    CHAR_LENGTH(`membres1`.`Nom`) || CHAR_LENGTH(`membres1`.`prenom`), CONCAT_WS('',   `membres1`.`Nom`, `membres1`.`prenom`), '') /* Demande par */" => "demande_par",
		"DATE_FORMAT(`intervention`.`date_demande`, '%Y/%m/%d')" => "date_demande",
		"IF(    CHAR_LENGTH(`membres2`.`Nom`) || CHAR_LENGTH(`membres2`.`prenom`), CONCAT_WS('',   `membres2`.`Nom`, `membres2`.`prenom`), '') /* Realise par */" => "realise_par",
		"DATE_FORMAT(`intervention`.`date_realisation`, '%Y/%m/%d')" => "date_realisation",
		"IF(    CHAR_LENGTH(`site_compostage1`.`nom_du_site`), CONCAT_WS('',   `site_compostage1`.`nom_du_site`), '') /* Pour site */" => "pour_site",
		"IF(    CHAR_LENGTH(`bacs_du_site1`.`type_de_bacs`) || CHAR_LENGTH(`site_compostage2`.`nom_du_site`), CONCAT_WS('',   `bacs_du_site1`.`type_de_bacs`, ' du site ', `site_compostage2`.`nom_du_site`), '') /* Pour bac */" => "pour_bac",
		"`intervention`.`type_intervention`" => "type_intervention",
		"`intervention`.`statut_intervention`" => "statut_intervention",
		"`intervention`.`description`" => "description",
		"`intervention`.`cree_par`" => "cree_par",
		"`intervention`.`date_maj`" => "date_maj",
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters = array(
		"`intervention`.`id`" => "ID",
		"IF(    CHAR_LENGTH(`membres1`.`Nom`) || CHAR_LENGTH(`membres1`.`prenom`), CONCAT_WS('',   `membres1`.`Nom`, `membres1`.`prenom`), '') /* Demande par */" => "Demande par",
		"`intervention`.`date_demande`" => "Date de la demande",
		"IF(    CHAR_LENGTH(`membres2`.`Nom`) || CHAR_LENGTH(`membres2`.`prenom`), CONCAT_WS('',   `membres2`.`Nom`, `membres2`.`prenom`), '') /* Realise par */" => "Realise par",
		"`intervention`.`date_realisation`" => "Date realisation",
		"IF(    CHAR_LENGTH(`site_compostage1`.`nom_du_site`), CONCAT_WS('',   `site_compostage1`.`nom_du_site`), '') /* Pour site */" => "Pour site",
		"IF(    CHAR_LENGTH(`bacs_du_site1`.`type_de_bacs`) || CHAR_LENGTH(`site_compostage2`.`nom_du_site`), CONCAT_WS('',   `bacs_du_site1`.`type_de_bacs`, ' du site ', `site_compostage2`.`nom_du_site`), '') /* Pour bac */" => "Pour bac",
		"`intervention`.`type_intervention`" => "Type intervention",
		"`intervention`.`statut_intervention`" => "Statut intervention",
		"`intervention`.`description`" => "Description",
		"`intervention`.`cree_par`" => "Cree par",
		"`intervention`.`date_maj`" => "Date creation",
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS = array(
		"`intervention`.`id`" => "id",
		"IF(    CHAR_LENGTH(`membres1`.`Nom`) || CHAR_LENGTH(`membres1`.`prenom`), CONCAT_WS('',   `membres1`.`Nom`, `membres1`.`prenom`), '') /* Demande par */" => "demande_par",
		"DATE_FORMAT(`intervention`.`date_demande`, '%Y/%m/%d')" => "date_demande",
		"IF(    CHAR_LENGTH(`membres2`.`Nom`) || CHAR_LENGTH(`membres2`.`prenom`), CONCAT_WS('',   `membres2`.`Nom`, `membres2`.`prenom`), '') /* Realise par */" => "realise_par",
		"DATE_FORMAT(`intervention`.`date_realisation`, '%Y/%m/%d')" => "date_realisation",
		"IF(    CHAR_LENGTH(`site_compostage1`.`nom_du_site`), CONCAT_WS('',   `site_compostage1`.`nom_du_site`), '') /* Pour site */" => "pour_site",
		"IF(    CHAR_LENGTH(`bacs_du_site1`.`type_de_bacs`) || CHAR_LENGTH(`site_compostage2`.`nom_du_site`), CONCAT_WS('',   `bacs_du_site1`.`type_de_bacs`, ' du site ', `site_compostage2`.`nom_du_site`), '') /* Pour bac */" => "pour_bac",
		"`intervention`.`type_intervention`" => "type_intervention",
		"`intervention`.`statut_intervention`" => "statut_intervention",
		"`intervention`.`description`" => "description",
		"`intervention`.`cree_par`" => "cree_par",
		"`intervention`.`date_maj`" => "date_maj",
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array('demande_par' => 'Demande par', 'realise_par' => 'Realise par', 'pour_site' => 'Pour site', 'pour_bac' => 'Pour bac', );

	$x->QueryFrom = "`intervention` LEFT JOIN `membres` as membres1 ON `membres1`.`id`=`intervention`.`demande_par` LEFT JOIN `membres` as membres2 ON `membres2`.`id`=`intervention`.`realise_par` LEFT JOIN `site_compostage` as site_compostage1 ON `site_compostage1`.`id`=`intervention`.`pour_site` LEFT JOIN `bacs_du_site` as bacs_du_site1 ON `bacs_du_site1`.`id`=`intervention`.`pour_bac` LEFT JOIN `site_compostage` as site_compostage2 ON `site_compostage2`.`id`=`bacs_du_site1`.`appartient_site` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = false;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "intervention_view.php";
	$x->RedirectAfterInsert = "intervention_view.php?SelectedID=#ID#";
	$x->TableTitle = "Intervention";
	$x->TableIcon = "resources/table_icons/alarm_bell.png";
	$x->PrimaryKey = "`intervention`.`id`";

	$x->ColWidth   = array(  150, 150, 150, 150, 150, 150, 150, 150);
	$x->ColCaption = array("Demande par", "Date de la demande", "Realise par", "Date realisation", "Pour site", "Pour bac", "Type intervention", "Statut intervention");
	$x->ColFieldName = array('demande_par', 'date_demande', 'realise_par', 'date_realisation', 'pour_site', 'pour_bac', 'type_intervention', 'statut_intervention');
	$x->ColNumber  = array(2, 3, 4, 5, 6, 7, 8, 9);

	// template paths below are based on the app main directory
	$x->Template = 'templates/intervention_templateTV.html';
	$x->SelectedTemplate = 'templates/intervention_templateTVS.html';
	$x->TemplateDV = 'templates/intervention_templateDV.html';
	$x->TemplateDVP = 'templates/intervention_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HighlightColor = '#FFF0C2';
	$x->HasCalculatedFields = false;

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))) { $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])) { // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `intervention`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='intervention' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])) { // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `intervention`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='intervention' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3) { // view all
		// no further action
	}elseif($perm[2]==0) { // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`intervention`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: intervention_init
	$render=TRUE;
	if(function_exists('intervention_init')) {
		$args=array();
		$render=intervention_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: intervention_header
	$headerCode='';
	if(function_exists('intervention_header')) {
		$args=array();
		$headerCode=intervention_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode) {
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: intervention_footer
	$footerCode='';
	if(function_exists('intervention_footer')) {
		$args=array();
		$footerCode=intervention_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode) {
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>