<?php

// Data functions (insert, update, delete, form) for table membres

// This script and data application were generated by AppGini 5.82
// Download AppGini for free from https://bigprof.com/appgini/download/

function membres_insert() {
	global $Translation;

	// mm: can member insert record?
	$arrPerm = getTablePermissions('membres');
	if(!$arrPerm[1]) return false;

	$data = array();
	$data['Nom'] = $_REQUEST['Nom'];
		if($data['Nom'] == empty_lookup_value) { $data['Nom'] = ''; }
	$data['prenom'] = $_REQUEST['prenom'];
		if($data['prenom'] == empty_lookup_value) { $data['prenom'] = ''; }
	$data['statut'] = $_REQUEST['statut'];
		if($data['statut'] == empty_lookup_value) { $data['statut'] = ''; }
	$data['adresse_du_membre'] = br2nl($_REQUEST['adresse_du_membre']);
	$data['email_membre'] = $_REQUEST['email_membre'];
		if($data['email_membre'] == empty_lookup_value) { $data['email_membre'] = ''; }
	$data['Telephone_membre'] = $_REQUEST['Telephone_membre'];
		if($data['Telephone_membre'] == empty_lookup_value) { $data['Telephone_membre'] = ''; }
	if($data['statut'] == '') $data['statut'] = "habitant";

	// hook: membres_before_insert
	if(function_exists('membres_before_insert')) {
		$args = array();
		if(!membres_before_insert($data, getMemberInfo(), $args)) { return false; }
	}

	$error = '';
	// set empty fields to NULL
	$data = array_map(function($v) { return ($v === '' ? NULL : $v); }, $data);
	insert('membres', backtick_keys_once($data), $error);
	if($error)
		die("{$error}<br><a href=\"#\" onclick=\"history.go(-1);\">{$Translation['< back']}</a>");

	$recID = db_insert_id(db_link());

	// hook: membres_after_insert
	if(function_exists('membres_after_insert')) {
		$res = sql("select * from `membres` where `id`='" . makeSafe($recID, false) . "' limit 1", $eo);
		if($row = db_fetch_assoc($res)) {
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args=array();
		if(!membres_after_insert($data, getMemberInfo(), $args)) { return $recID; }
	}

	// mm: save ownership data
	set_record_owner('membres', $recID, getLoggedMemberID());

	// if this record is a copy of another record, copy children if applicable
	if(!empty($_REQUEST['SelectedID'])) membres_copy_children($recID, $_REQUEST['SelectedID']);

	return $recID;
}

function membres_copy_children($destination_id, $source_id) {
	global $Translation;
	$requests = array(); // array of curl handlers for launching insert requests
	$eo = array('silentErrors' => true);
	$uploads_dir = realpath(dirname(__FILE__) . '/../' . $Translation['ImageFolder']);
	$safe_sid = makeSafe($source_id);

	// launch requests, asynchronously
	curl_batch($requests);
}

function membres_delete($selected_id, $AllowDeleteOfParents=false, $skipChecks=false) {
	// insure referential integrity ...
	global $Translation;
	$selected_id=makeSafe($selected_id);

	// mm: can member delete record?
	$arrPerm=getTablePermissions('membres');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='membres' and pkValue='$selected_id'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='membres' and pkValue='$selected_id'");
	if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3) { // allow delete?
		// delete allowed, so continue ...
	}else{
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: membres_before_delete
	if(function_exists('membres_before_delete')) {
		$args=array();
		if(!membres_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'];
	}

	// child table: depots
	$res = sql("select `id` from `membres` where `id`='$selected_id'", $eo);
	$id = db_fetch_row($res);
	$rires = sql("select count(1) from `depots` where `par_le_membre`='".addslashes($id[0])."'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "depots", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "depots", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input type=\"button\" class=\"button\" value=\"".$Translation['yes']."\" onClick=\"window.location='membres_view.php?SelectedID=".urlencode($selected_id)."&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input type=\"button\" class=\"button\" value=\"".$Translation['no']."\" onClick=\"window.location='membres_view.php?SelectedID=".urlencode($selected_id)."';\">", $RetMsg);
		return $RetMsg;
	}

	// child table: transferts
	$res = sql("select `id` from `membres` where `id`='$selected_id'", $eo);
	$id = db_fetch_row($res);
	$rires = sql("select count(1) from `transferts` where `par_le_membre`='".addslashes($id[0])."'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "transferts", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "transferts", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input type=\"button\" class=\"button\" value=\"".$Translation['yes']."\" onClick=\"window.location='membres_view.php?SelectedID=".urlencode($selected_id)."&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input type=\"button\" class=\"button\" value=\"".$Translation['no']."\" onClick=\"window.location='membres_view.php?SelectedID=".urlencode($selected_id)."';\">", $RetMsg);
		return $RetMsg;
	}

	// child table: intervention
	$res = sql("select `id` from `membres` where `id`='$selected_id'", $eo);
	$id = db_fetch_row($res);
	$rires = sql("select count(1) from `intervention` where `demande_par`='".addslashes($id[0])."'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "intervention", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "intervention", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input type=\"button\" class=\"button\" value=\"".$Translation['yes']."\" onClick=\"window.location='membres_view.php?SelectedID=".urlencode($selected_id)."&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input type=\"button\" class=\"button\" value=\"".$Translation['no']."\" onClick=\"window.location='membres_view.php?SelectedID=".urlencode($selected_id)."';\">", $RetMsg);
		return $RetMsg;
	}

	// child table: intervention
	$res = sql("select `id` from `membres` where `id`='$selected_id'", $eo);
	$id = db_fetch_row($res);
	$rires = sql("select count(1) from `intervention` where `realise_par`='".addslashes($id[0])."'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "intervention", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "intervention", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input type=\"button\" class=\"button\" value=\"".$Translation['yes']."\" onClick=\"window.location='membres_view.php?SelectedID=".urlencode($selected_id)."&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input type=\"button\" class=\"button\" value=\"".$Translation['no']."\" onClick=\"window.location='membres_view.php?SelectedID=".urlencode($selected_id)."';\">", $RetMsg);
		return $RetMsg;
	}

	sql("delete from `membres` where `id`='$selected_id'", $eo);

	// hook: membres_after_delete
	if(function_exists('membres_after_delete')) {
		$args=array();
		membres_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("delete from membership_userrecords where tableName='membres' and pkValue='$selected_id'", $eo);
}

function membres_update($selected_id) {
	global $Translation;

	// mm: can member edit record?
	$arrPerm=getTablePermissions('membres');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='membres' and pkValue='".makeSafe($selected_id)."'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='membres' and pkValue='".makeSafe($selected_id)."'");
	if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3) { // allow update?
		// update allowed, so continue ...
	}else{
		return false;
	}

	$data['Nom'] = makeSafe($_REQUEST['Nom']);
		if($data['Nom'] == empty_lookup_value) { $data['Nom'] = ''; }
	$data['prenom'] = makeSafe($_REQUEST['prenom']);
		if($data['prenom'] == empty_lookup_value) { $data['prenom'] = ''; }
	$data['statut'] = makeSafe($_REQUEST['statut']);
		if($data['statut'] == empty_lookup_value) { $data['statut'] = ''; }
	$data['adresse_du_membre'] = br2nl(makeSafe($_REQUEST['adresse_du_membre']));
	$data['email_membre'] = makeSafe($_REQUEST['email_membre']);
		if($data['email_membre'] == empty_lookup_value) { $data['email_membre'] = ''; }
	$data['Telephone_membre'] = makeSafe($_REQUEST['Telephone_membre']);
		if($data['Telephone_membre'] == empty_lookup_value) { $data['Telephone_membre'] = ''; }
	$data['selectedID'] = makeSafe($selected_id);

	// hook: membres_before_update
	if(function_exists('membres_before_update')) {
		$args = array();
		if(!membres_before_update($data, getMemberInfo(), $args)) { return false; }
	}

	$o = array('silentErrors' => true);
	sql('update `membres` set       `Nom`=' . (($data['Nom'] !== '' && $data['Nom'] !== NULL) ? "'{$data['Nom']}'" : 'NULL') . ', `prenom`=' . (($data['prenom'] !== '' && $data['prenom'] !== NULL) ? "'{$data['prenom']}'" : 'NULL') . ', `statut`=' . (($data['statut'] !== '' && $data['statut'] !== NULL) ? "'{$data['statut']}'" : 'NULL') . ', `adresse_du_membre`=' . (($data['adresse_du_membre'] !== '' && $data['adresse_du_membre'] !== NULL) ? "'{$data['adresse_du_membre']}'" : 'NULL') . ', `email_membre`=' . (($data['email_membre'] !== '' && $data['email_membre'] !== NULL) ? "'{$data['email_membre']}'" : 'NULL') . ', `Telephone_membre`=' . (($data['Telephone_membre'] !== '' && $data['Telephone_membre'] !== NULL) ? "'{$data['Telephone_membre']}'" : 'NULL') . " where `id`='".makeSafe($selected_id)."'", $o);
	if($o['error']!='') {
		echo $o['error'];
		echo '<a href="membres_view.php?SelectedID='.urlencode($selected_id)."\">{$Translation['< back']}</a>";
		exit;
	}


	// hook: membres_after_update
	if(function_exists('membres_after_update')) {
		$res = sql("SELECT * FROM `membres` WHERE `id`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) {
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = $data['id'];
		$args = array();
		if(!membres_after_update($data, getMemberInfo(), $args)) { return; }
	}

	// mm: update ownership data
	sql("update `membership_userrecords` set `dateUpdated`='" . time() . "' where `tableName`='membres' and `pkValue`='" . makeSafe($selected_id) . "'", $eo);

}

function membres_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $ShowCancel = 0, $TemplateDV = '', $TemplateDVP = '') {
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;

	// mm: get table permissions
	$arrPerm=getTablePermissions('membres');
	if(!$arrPerm[1] && $selected_id=='') { return ''; }
	$AllowInsert = ($arrPerm[1] ? true : false);
	// print preview?
	$dvprint = false;
	if($selected_id && $_REQUEST['dvprint_x'] != '') {
		$dvprint = true;
	}


	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: statut
	$combo_statut = new Combo;
	$combo_statut->ListType = 0;
	$combo_statut->MultipleSeparator = ', ';
	$combo_statut->ListBoxHeight = 10;
	$combo_statut->RadiosPerLine = 1;
	if(is_file(dirname(__FILE__).'/hooks/membres.statut.csv')) {
		$statut_data = addslashes(implode('', @file(dirname(__FILE__).'/hooks/membres.statut.csv')));
		$combo_statut->ListItem = explode('||', entitiesToUTF8(convertLegacyOptions($statut_data)));
		$combo_statut->ListData = $combo_statut->ListItem;
	}else{
		$combo_statut->ListItem = explode('||', entitiesToUTF8(convertLegacyOptions("habitant;;animateur;;technicien;;administrateur")));
		$combo_statut->ListData = $combo_statut->ListItem;
	}
	$combo_statut->SelectName = 'statut';

	if($selected_id) {
		// mm: check member permissions
		if(!$arrPerm[2]) {
			return "";
		}
		// mm: who is the owner?
		$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='membres' and pkValue='".makeSafe($selected_id)."'");
		$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='membres' and pkValue='".makeSafe($selected_id)."'");
		if($arrPerm[2]==1 && getLoggedMemberID()!=$ownerMemberID) {
			return "";
		}
		if($arrPerm[2]==2 && getLoggedGroupID()!=$ownerGroupID) {
			return "";
		}

		// can edit?
		if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3) {
			$AllowUpdate=1;
		}else{
			$AllowUpdate=0;
		}

		$res = sql("SELECT * FROM `membres` WHERE `id`='" . makeSafe($selected_id) . "'", $eo);
		if(!($row = db_fetch_array($res))) {
			return error_message($Translation['No records found'], 'membres_view.php', false);
		}
		$combo_statut->SelectedData = $row['statut'];
		$urow = $row; /* unsanitized data */
		$hc = new CI_Input();
		$row = $hc->xss_clean($row); /* sanitize data */
	} else {
		$combo_statut->SelectedText = ( $_REQUEST['FilterField'][1]=='4' && $_REQUEST['FilterOperator'][1]=='<=>' ? (get_magic_quotes_gpc() ? stripslashes($_REQUEST['FilterValue'][1]) : $_REQUEST['FilterValue'][1]) : "habitant");
	}
	$combo_statut->Render();

	ob_start();
	?>

	<script>
		// initial lookup values

		jQuery(function() {
			setTimeout(function() {
			}, 10); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_contents());
	ob_end_clean();


	// code for template based detail view forms

	// open the detail view template
	if($dvprint) {
		$template_file = is_file("./{$TemplateDVP}") ? "./{$TemplateDVP}" : './templates/membres_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	}else{
		$template_file = is_file("./{$TemplateDV}") ? "./{$TemplateDV}" : './templates/membres_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Membre details', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', ($_REQUEST['Embedded'] ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($AllowInsert) {
		if(!$selected_id) $templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return membres_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return membres_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	}else{
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if($_REQUEST['Embedded']) {
		$backAction = 'AppGini.closeParentModal(); return false;';
	}else{
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id) {
		if(!$_REQUEST['Embedded']) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$j(\'form\').eq(0).prop(\'novalidate\', true); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate) {
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return membres_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		}else{
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3) { // allow delete?
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" onclick="return confirm(\'' . $Translation['are you sure?'] . '\');" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		}else{
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	}else{
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', ($ShowCancel ? '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>' : ''), $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$AllowInsert) || (!$selected_id && !$AllowInsert)) {
		$jsReadOnly .= "\tjQuery('#Nom').replaceWith('<div class=\"form-control-static\" id=\"Nom\">' + (jQuery('#Nom').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#prenom').replaceWith('<div class=\"form-control-static\" id=\"prenom\">' + (jQuery('#prenom').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#statut').replaceWith('<div class=\"form-control-static\" id=\"statut\">' + (jQuery('#statut').val() || '') + '</div>'); jQuery('#statut-multi-selection-help').hide();\n";
		$jsReadOnly .= "\tjQuery('#adresse_du_membre').replaceWith('<div class=\"form-control-static\" id=\"adresse_du_membre\">' + (jQuery('#adresse_du_membre').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#email_membre').replaceWith('<div class=\"form-control-static\" id=\"email_membre\">' + (jQuery('#email_membre').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#Telephone_membre').replaceWith('<div class=\"form-control-static\" id=\"Telephone_membre\">' + (jQuery('#Telephone_membre').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	}elseif($AllowInsert) {
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
			$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(statut)%%>', $combo_statut->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(statut)%%>', $combo_statut->SelectedData, $templateCode);

	/* lookup fields array: 'lookup field name' => array('parent table name', 'lookup field caption') */
	$lookup_fields = array();
	foreach($lookup_fields as $luf => $ptfc) {
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']) {
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent hspacer-md" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] && !$_REQUEST['Embedded']) {
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-success add_new_parent hspacer-md" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus-sign"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Nom)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(prenom)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(statut)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(adresse_du_membre)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(email_membre)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Telephone_membre)%%>', '', $templateCode);

	// process values
	if($selected_id) {
		if( $dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', safe_html($urow['id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', html_attr($row['id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode($urow['id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Nom)%%>', safe_html($urow['Nom']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Nom)%%>', html_attr($row['Nom']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Nom)%%>', urlencode($urow['Nom']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(prenom)%%>', safe_html($urow['prenom']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(prenom)%%>', html_attr($row['prenom']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(prenom)%%>', urlencode($urow['prenom']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(statut)%%>', safe_html($urow['statut']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(statut)%%>', html_attr($row['statut']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(statut)%%>', urlencode($urow['statut']), $templateCode);
		if($dvprint || (!$AllowUpdate && !$AllowInsert)) {
			$templateCode = str_replace('<%%VALUE(adresse_du_membre)%%>', safe_html($urow['adresse_du_membre']), $templateCode);
		}else{
			$templateCode = str_replace('<%%VALUE(adresse_du_membre)%%>', html_attr($row['adresse_du_membre']), $templateCode);
		}
		$templateCode = str_replace('<%%URLVALUE(adresse_du_membre)%%>', urlencode($urow['adresse_du_membre']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(email_membre)%%>', safe_html($urow['email_membre']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(email_membre)%%>', html_attr($row['email_membre']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(email_membre)%%>', urlencode($urow['email_membre']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Telephone_membre)%%>', safe_html($urow['Telephone_membre']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Telephone_membre)%%>', html_attr($row['Telephone_membre']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Telephone_membre)%%>', urlencode($urow['Telephone_membre']), $templateCode);
	}else{
		$templateCode = str_replace('<%%VALUE(id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Nom)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Nom)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(prenom)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(prenom)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(statut)%%>', 'habitant', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(statut)%%>', urlencode('habitant'), $templateCode);
		$templateCode = str_replace('<%%VALUE(adresse_du_membre)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(adresse_du_membre)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(email_membre)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(email_membre)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Telephone_membre)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Telephone_membre)%%>', urlencode(''), $templateCode);
	}

	// process translations
	foreach($Translation as $symbol=>$trans) {
		$templateCode = str_replace("<%%TRANSLATION($symbol)%%>", $trans, $templateCode);
	}

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if($_REQUEST['dvprint_x'] == '') {
		$templateCode .= "\n\n<script>\$j(function() {\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption) {
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id) {
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('membres');
	if($selected_id) {
		$jdata = get_joined_record('membres', $selected_id);
		if($jdata === false) $jdata = get_defaults('membres');
		$rdata = $row;
	}
	$templateCode .= loadView('membres-ajax-cache', array('rdata' => $rdata, 'jdata' => $jdata));

	// hook: membres_dv
	if(function_exists('membres_dv')) {
		$args=array();
		membres_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}
?>