<?php
// This script and data application were generated by AppGini 5.82
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/membres.php");
	include("$currDir/membres_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('membres');
	if(!$perm[0]) {
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "membres";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = array(
		"`membres`.`id`" => "id",
		"`membres`.`Nom`" => "Nom",
		"`membres`.`prenom`" => "prenom",
		"`membres`.`statut`" => "statut",
		"`membres`.`adresse_du_membre`" => "adresse_du_membre",
		"`membres`.`email_membre`" => "email_membre",
		"`membres`.`Telephone_membre`" => "Telephone_membre",
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(
		1 => '`membres`.`id`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => 5,
		6 => 6,
		7 => 7,
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = array(
		"`membres`.`id`" => "id",
		"`membres`.`Nom`" => "Nom",
		"`membres`.`prenom`" => "prenom",
		"`membres`.`statut`" => "statut",
		"`membres`.`adresse_du_membre`" => "adresse_du_membre",
		"`membres`.`email_membre`" => "email_membre",
		"`membres`.`Telephone_membre`" => "Telephone_membre",
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters = array(
		"`membres`.`id`" => "ID",
		"`membres`.`Nom`" => "Nom",
		"`membres`.`prenom`" => "Prenom",
		"`membres`.`statut`" => "Statut",
		"`membres`.`adresse_du_membre`" => "Adresse du membre",
		"`membres`.`email_membre`" => "Email membre",
		"`membres`.`Telephone_membre`" => "Telephone membre",
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS = array(
		"`membres`.`id`" => "id",
		"`membres`.`Nom`" => "Nom",
		"`membres`.`prenom`" => "prenom",
		"`membres`.`statut`" => "statut",
		"`membres`.`adresse_du_membre`" => "adresse_du_membre",
		"`membres`.`email_membre`" => "email_membre",
		"`membres`.`Telephone_membre`" => "Telephone_membre",
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array();

	$x->QueryFrom = "`membres` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = false;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 0;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "membres_view.php";
	$x->RedirectAfterInsert = "membres_view.php?SelectedID=#ID#";
	$x->TableTitle = "Membres";
	$x->TableIcon = "resources/table_icons/group.png";
	$x->PrimaryKey = "`membres`.`id`";

	$x->ColWidth   = array(  150, 150, 150, 150, 150, 150);
	$x->ColCaption = array("Nom", "Prenom", "Statut", "Adresse du membre", "Email membre", "Telephone membre");
	$x->ColFieldName = array('Nom', 'prenom', 'statut', 'adresse_du_membre', 'email_membre', 'Telephone_membre');
	$x->ColNumber  = array(2, 3, 4, 5, 6, 7);

	// template paths below are based on the app main directory
	$x->Template = 'templates/membres_templateTV.html';
	$x->SelectedTemplate = 'templates/membres_templateTVS.html';
	$x->TemplateDV = 'templates/membres_templateDV.html';
	$x->TemplateDVP = 'templates/membres_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HighlightColor = '#FFF0C2';
	$x->HasCalculatedFields = false;

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))) { $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])) { // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `membres`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='membres' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])) { // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `membres`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='membres' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3) { // view all
		// no further action
	}elseif($perm[2]==0) { // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`membres`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: membres_init
	$render=TRUE;
	if(function_exists('membres_init')) {
		$args=array();
		$render=membres_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: membres_header
	$headerCode='';
	if(function_exists('membres_header')) {
		$args=array();
		$headerCode=membres_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode) {
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: membres_footer
	$footerCode='';
	if(function_exists('membres_footer')) {
		$args=array();
		$footerCode=membres_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode) {
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>