<?php

// Data functions (insert, update, delete, form) for table site_compostage

// This script and data application were generated by AppGini 5.82
// Download AppGini for free from https://bigprof.com/appgini/download/

function site_compostage_insert() {
	global $Translation;

	// mm: can member insert record?
	$arrPerm = getTablePermissions('site_compostage');
	if(!$arrPerm[1]) return false;

	$data = array();
	$data['nom_du_site'] = $_REQUEST['nom_du_site'];
		if($data['nom_du_site'] == empty_lookup_value) { $data['nom_du_site'] = ''; }
	$data['adresse_postale'] = $_REQUEST['adresse_postale'];
		if($data['adresse_postale'] == empty_lookup_value) { $data['adresse_postale'] = ''; }
	$data['acces_au_site'] = $_REQUEST['acces_au_site'];
		if($data['acces_au_site'] == empty_lookup_value) { $data['acces_au_site'] = ''; }
	$data['type_de_site'] = $_REQUEST['type_de_site'];
		if($data['type_de_site'] == empty_lookup_value) { $data['type_de_site'] = ''; }
	$data['nom_du_responsable'] = $_REQUEST['nom_du_responsable'];
		if($data['nom_du_responsable'] == empty_lookup_value) { $data['nom_du_responsable'] = ''; }
	$data['email_du_responsable'] = $_REQUEST['email_du_responsable'];
		if($data['email_du_responsable'] == empty_lookup_value) { $data['email_du_responsable'] = ''; }
	$data['Telephone_du_responsable'] = $_REQUEST['Telephone_du_responsable'];
		if($data['Telephone_du_responsable'] == empty_lookup_value) { $data['Telephone_du_responsable'] = ''; }
	$data['Commentaires'] = $_REQUEST['Commentaires'];
		if($data['Commentaires'] == empty_lookup_value) { $data['Commentaires'] = ''; }
	if($data['email_du_responsable'] == '') $data['email_du_responsable'] = "adresse@email.com";

	// hook: site_compostage_before_insert
	if(function_exists('site_compostage_before_insert')) {
		$args = array();
		if(!site_compostage_before_insert($data, getMemberInfo(), $args)) { return false; }
	}

	$error = '';
	// set empty fields to NULL
	$data = array_map(function($v) { return ($v === '' ? NULL : $v); }, $data);
	insert('site_compostage', backtick_keys_once($data), $error);
	if($error)
		die("{$error}<br><a href=\"#\" onclick=\"history.go(-1);\">{$Translation['< back']}</a>");

	$recID = db_insert_id(db_link());

	// hook: site_compostage_after_insert
	if(function_exists('site_compostage_after_insert')) {
		$res = sql("select * from `site_compostage` where `id`='" . makeSafe($recID, false) . "' limit 1", $eo);
		if($row = db_fetch_assoc($res)) {
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args=array();
		if(!site_compostage_after_insert($data, getMemberInfo(), $args)) { return $recID; }
	}

	// mm: save ownership data
	set_record_owner('site_compostage', $recID, getLoggedMemberID());

	// if this record is a copy of another record, copy children if applicable
	if(!empty($_REQUEST['SelectedID'])) site_compostage_copy_children($recID, $_REQUEST['SelectedID']);

	return $recID;
}

function site_compostage_copy_children($destination_id, $source_id) {
	global $Translation;
	$requests = array(); // array of curl handlers for launching insert requests
	$eo = array('silentErrors' => true);
	$uploads_dir = realpath(dirname(__FILE__) . '/../' . $Translation['ImageFolder']);
	$safe_sid = makeSafe($source_id);

	// launch requests, asynchronously
	curl_batch($requests);
}

function site_compostage_delete($selected_id, $AllowDeleteOfParents=false, $skipChecks=false) {
	// insure referential integrity ...
	global $Translation;
	$selected_id=makeSafe($selected_id);

	// mm: can member delete record?
	$arrPerm=getTablePermissions('site_compostage');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='site_compostage' and pkValue='$selected_id'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='site_compostage' and pkValue='$selected_id'");
	if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3) { // allow delete?
		// delete allowed, so continue ...
	}else{
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: site_compostage_before_delete
	if(function_exists('site_compostage_before_delete')) {
		$args=array();
		if(!site_compostage_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'];
	}

	// child table: depots
	$res = sql("select `id` from `site_compostage` where `id`='$selected_id'", $eo);
	$id = db_fetch_row($res);
	$rires = sql("select count(1) from `depots` where `sur_le_site`='".addslashes($id[0])."'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "depots", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "depots", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input type=\"button\" class=\"button\" value=\"".$Translation['yes']."\" onClick=\"window.location='site_compostage_view.php?SelectedID=".urlencode($selected_id)."&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input type=\"button\" class=\"button\" value=\"".$Translation['no']."\" onClick=\"window.location='site_compostage_view.php?SelectedID=".urlencode($selected_id)."';\">", $RetMsg);
		return $RetMsg;
	}

	// child table: bacs_du_site
	$res = sql("select `id` from `site_compostage` where `id`='$selected_id'", $eo);
	$id = db_fetch_row($res);
	$rires = sql("select count(1) from `bacs_du_site` where `appartient_site`='".addslashes($id[0])."'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "bacs_du_site", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "bacs_du_site", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input type=\"button\" class=\"button\" value=\"".$Translation['yes']."\" onClick=\"window.location='site_compostage_view.php?SelectedID=".urlencode($selected_id)."&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input type=\"button\" class=\"button\" value=\"".$Translation['no']."\" onClick=\"window.location='site_compostage_view.php?SelectedID=".urlencode($selected_id)."';\">", $RetMsg);
		return $RetMsg;
	}

	// child table: transferts
	$res = sql("select `id` from `site_compostage` where `id`='$selected_id'", $eo);
	$id = db_fetch_row($res);
	$rires = sql("select count(1) from `transferts` where `sur_le_site`='".addslashes($id[0])."'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "transferts", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "transferts", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input type=\"button\" class=\"button\" value=\"".$Translation['yes']."\" onClick=\"window.location='site_compostage_view.php?SelectedID=".urlencode($selected_id)."&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input type=\"button\" class=\"button\" value=\"".$Translation['no']."\" onClick=\"window.location='site_compostage_view.php?SelectedID=".urlencode($selected_id)."';\">", $RetMsg);
		return $RetMsg;
	}

	// child table: intervention
	$res = sql("select `id` from `site_compostage` where `id`='$selected_id'", $eo);
	$id = db_fetch_row($res);
	$rires = sql("select count(1) from `intervention` where `pour_site`='".addslashes($id[0])."'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "intervention", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "intervention", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input type=\"button\" class=\"button\" value=\"".$Translation['yes']."\" onClick=\"window.location='site_compostage_view.php?SelectedID=".urlencode($selected_id)."&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input type=\"button\" class=\"button\" value=\"".$Translation['no']."\" onClick=\"window.location='site_compostage_view.php?SelectedID=".urlencode($selected_id)."';\">", $RetMsg);
		return $RetMsg;
	}

	sql("delete from `site_compostage` where `id`='$selected_id'", $eo);

	// hook: site_compostage_after_delete
	if(function_exists('site_compostage_after_delete')) {
		$args=array();
		site_compostage_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("delete from membership_userrecords where tableName='site_compostage' and pkValue='$selected_id'", $eo);
}

function site_compostage_update($selected_id) {
	global $Translation;

	// mm: can member edit record?
	$arrPerm=getTablePermissions('site_compostage');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='site_compostage' and pkValue='".makeSafe($selected_id)."'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='site_compostage' and pkValue='".makeSafe($selected_id)."'");
	if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3) { // allow update?
		// update allowed, so continue ...
	}else{
		return false;
	}

	$data['nom_du_site'] = makeSafe($_REQUEST['nom_du_site']);
		if($data['nom_du_site'] == empty_lookup_value) { $data['nom_du_site'] = ''; }
	$data['adresse_postale'] = makeSafe($_REQUEST['adresse_postale']);
		if($data['adresse_postale'] == empty_lookup_value) { $data['adresse_postale'] = ''; }
	$data['acces_au_site'] = makeSafe($_REQUEST['acces_au_site']);
		if($data['acces_au_site'] == empty_lookup_value) { $data['acces_au_site'] = ''; }
	$data['type_de_site'] = makeSafe($_REQUEST['type_de_site']);
		if($data['type_de_site'] == empty_lookup_value) { $data['type_de_site'] = ''; }
	$data['nom_du_responsable'] = makeSafe($_REQUEST['nom_du_responsable']);
		if($data['nom_du_responsable'] == empty_lookup_value) { $data['nom_du_responsable'] = ''; }
	$data['email_du_responsable'] = makeSafe($_REQUEST['email_du_responsable']);
		if($data['email_du_responsable'] == empty_lookup_value) { $data['email_du_responsable'] = ''; }
	$data['Telephone_du_responsable'] = makeSafe($_REQUEST['Telephone_du_responsable']);
		if($data['Telephone_du_responsable'] == empty_lookup_value) { $data['Telephone_du_responsable'] = ''; }
	$data['Commentaires'] = makeSafe($_REQUEST['Commentaires']);
		if($data['Commentaires'] == empty_lookup_value) { $data['Commentaires'] = ''; }
	$data['selectedID'] = makeSafe($selected_id);

	// hook: site_compostage_before_update
	if(function_exists('site_compostage_before_update')) {
		$args = array();
		if(!site_compostage_before_update($data, getMemberInfo(), $args)) { return false; }
	}

	$o = array('silentErrors' => true);
	sql('update `site_compostage` set       `nom_du_site`=' . (($data['nom_du_site'] !== '' && $data['nom_du_site'] !== NULL) ? "'{$data['nom_du_site']}'" : 'NULL') . ', `adresse_postale`=' . (($data['adresse_postale'] !== '' && $data['adresse_postale'] !== NULL) ? "'{$data['adresse_postale']}'" : 'NULL') . ', `acces_au_site`=' . (($data['acces_au_site'] !== '' && $data['acces_au_site'] !== NULL) ? "'{$data['acces_au_site']}'" : 'NULL') . ', `type_de_site`=' . (($data['type_de_site'] !== '' && $data['type_de_site'] !== NULL) ? "'{$data['type_de_site']}'" : 'NULL') . ', `nom_du_responsable`=' . (($data['nom_du_responsable'] !== '' && $data['nom_du_responsable'] !== NULL) ? "'{$data['nom_du_responsable']}'" : 'NULL') . ', `email_du_responsable`=' . (($data['email_du_responsable'] !== '' && $data['email_du_responsable'] !== NULL) ? "'{$data['email_du_responsable']}'" : 'NULL') . ', `Telephone_du_responsable`=' . (($data['Telephone_du_responsable'] !== '' && $data['Telephone_du_responsable'] !== NULL) ? "'{$data['Telephone_du_responsable']}'" : 'NULL') . ', `Commentaires`=' . (($data['Commentaires'] !== '' && $data['Commentaires'] !== NULL) ? "'{$data['Commentaires']}'" : 'NULL') . " where `id`='".makeSafe($selected_id)."'", $o);
	if($o['error']!='') {
		echo $o['error'];
		echo '<a href="site_compostage_view.php?SelectedID='.urlencode($selected_id)."\">{$Translation['< back']}</a>";
		exit;
	}


	// hook: site_compostage_after_update
	if(function_exists('site_compostage_after_update')) {
		$res = sql("SELECT * FROM `site_compostage` WHERE `id`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) {
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = $data['id'];
		$args = array();
		if(!site_compostage_after_update($data, getMemberInfo(), $args)) { return; }
	}

	// mm: update ownership data
	sql("update `membership_userrecords` set `dateUpdated`='" . time() . "' where `tableName`='site_compostage' and `pkValue`='" . makeSafe($selected_id) . "'", $eo);

}

function site_compostage_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $ShowCancel = 0, $TemplateDV = '', $TemplateDVP = '') {
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;

	// mm: get table permissions
	$arrPerm=getTablePermissions('site_compostage');
	if(!$arrPerm[1] && $selected_id=='') { return ''; }
	$AllowInsert = ($arrPerm[1] ? true : false);
	// print preview?
	$dvprint = false;
	if($selected_id && $_REQUEST['dvprint_x'] != '') {
		$dvprint = true;
	}


	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: type_de_site
	$combo_type_de_site = new Combo;
	$combo_type_de_site->ListType = 0;
	$combo_type_de_site->MultipleSeparator = ', ';
	$combo_type_de_site->ListBoxHeight = 10;
	$combo_type_de_site->RadiosPerLine = 1;
	if(is_file(dirname(__FILE__).'/hooks/site_compostage.type_de_site.csv')) {
		$type_de_site_data = addslashes(implode('', @file(dirname(__FILE__).'/hooks/site_compostage.type_de_site.csv')));
		$combo_type_de_site->ListItem = explode('||', entitiesToUTF8(convertLegacyOptions($type_de_site_data)));
		$combo_type_de_site->ListData = $combo_type_de_site->ListItem;
	}else{
		$combo_type_de_site->ListItem = explode('||', entitiesToUTF8(convertLegacyOptions("Ecole;;Partag&#233;")));
		$combo_type_de_site->ListData = $combo_type_de_site->ListItem;
	}
	$combo_type_de_site->SelectName = 'type_de_site';

	if($selected_id) {
		// mm: check member permissions
		if(!$arrPerm[2]) {
			return "";
		}
		// mm: who is the owner?
		$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='site_compostage' and pkValue='".makeSafe($selected_id)."'");
		$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='site_compostage' and pkValue='".makeSafe($selected_id)."'");
		if($arrPerm[2]==1 && getLoggedMemberID()!=$ownerMemberID) {
			return "";
		}
		if($arrPerm[2]==2 && getLoggedGroupID()!=$ownerGroupID) {
			return "";
		}

		// can edit?
		if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3) {
			$AllowUpdate=1;
		}else{
			$AllowUpdate=0;
		}

		$res = sql("SELECT * FROM `site_compostage` WHERE `id`='" . makeSafe($selected_id) . "'", $eo);
		if(!($row = db_fetch_array($res))) {
			return error_message($Translation['No records found'], 'site_compostage_view.php', false);
		}
		$combo_type_de_site->SelectedData = $row['type_de_site'];
		$urow = $row; /* unsanitized data */
		$hc = new CI_Input();
		$row = $hc->xss_clean($row); /* sanitize data */
	} else {
		$combo_type_de_site->SelectedText = ( $_REQUEST['FilterField'][1]=='5' && $_REQUEST['FilterOperator'][1]=='<=>' ? (get_magic_quotes_gpc() ? stripslashes($_REQUEST['FilterValue'][1]) : $_REQUEST['FilterValue'][1]) : "");
	}
	$combo_type_de_site->Render();

	ob_start();
	?>

	<script>
		// initial lookup values

		jQuery(function() {
			setTimeout(function() {
			}, 10); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_contents());
	ob_end_clean();


	// code for template based detail view forms

	// open the detail view template
	if($dvprint) {
		$template_file = is_file("./{$TemplateDVP}") ? "./{$TemplateDVP}" : './templates/site_compostage_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	}else{
		$template_file = is_file("./{$TemplateDV}") ? "./{$TemplateDV}" : './templates/site_compostage_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Site compostage details', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', ($_REQUEST['Embedded'] ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($AllowInsert) {
		if(!$selected_id) $templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return site_compostage_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return site_compostage_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	}else{
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if($_REQUEST['Embedded']) {
		$backAction = 'AppGini.closeParentModal(); return false;';
	}else{
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id) {
		if(!$_REQUEST['Embedded']) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$j(\'form\').eq(0).prop(\'novalidate\', true); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate) {
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return site_compostage_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		}else{
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3) { // allow delete?
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" onclick="return confirm(\'' . $Translation['are you sure?'] . '\');" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		}else{
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	}else{
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', ($ShowCancel ? '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>' : ''), $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$AllowInsert) || (!$selected_id && !$AllowInsert)) {
		$jsReadOnly .= "\tjQuery('#nom_du_site').replaceWith('<div class=\"form-control-static\" id=\"nom_du_site\">' + (jQuery('#nom_du_site').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#adresse_postale').replaceWith('<div class=\"form-control-static\" id=\"adresse_postale\">' + (jQuery('#adresse_postale').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#acces_au_site').replaceWith('');\n";
		$jsReadOnly .= "\tjQuery('#acces_au_site, #acces_au_site-edit-link').hide();\n";
		$jsReadOnly .= "\tjQuery('#type_de_site').replaceWith('<div class=\"form-control-static\" id=\"type_de_site\">' + (jQuery('#type_de_site').val() || '') + '</div>'); jQuery('#type_de_site-multi-selection-help').hide();\n";
		$jsReadOnly .= "\tjQuery('#nom_du_responsable').replaceWith('<div class=\"form-control-static\" id=\"nom_du_responsable\">' + (jQuery('#nom_du_responsable').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#email_du_responsable').replaceWith('<div class=\"form-control-static\" id=\"email_du_responsable\">' + (jQuery('#email_du_responsable').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#email_du_responsable, #email_du_responsable-edit-link').hide();\n";
		$jsReadOnly .= "\tjQuery('#Telephone_du_responsable').replaceWith('<div class=\"form-control-static\" id=\"Telephone_du_responsable\">' + (jQuery('#Telephone_du_responsable').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	}elseif($AllowInsert) {
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
			$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(type_de_site)%%>', $combo_type_de_site->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(type_de_site)%%>', $combo_type_de_site->SelectedData, $templateCode);

	/* lookup fields array: 'lookup field name' => array('parent table name', 'lookup field caption') */
	$lookup_fields = array();
	foreach($lookup_fields as $luf => $ptfc) {
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']) {
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent hspacer-md" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] && !$_REQUEST['Embedded']) {
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-success add_new_parent hspacer-md" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus-sign"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(nom_du_site)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(adresse_postale)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(acces_au_site)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(type_de_site)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(nom_du_responsable)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(email_du_responsable)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Telephone_du_responsable)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Commentaires)%%>', '', $templateCode);

	// process values
	if($selected_id) {
		if( $dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', safe_html($urow['id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', html_attr($row['id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode($urow['id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(nom_du_site)%%>', safe_html($urow['nom_du_site']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(nom_du_site)%%>', html_attr($row['nom_du_site']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(nom_du_site)%%>', urlencode($urow['nom_du_site']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(adresse_postale)%%>', safe_html($urow['adresse_postale']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(adresse_postale)%%>', html_attr($row['adresse_postale']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(adresse_postale)%%>', urlencode($urow['adresse_postale']), $templateCode);
		$templateCode = str_replace('<%%VALUE(acces_au_site)%%>', html_attr($row['acces_au_site']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(acces_au_site)%%>', urlencode($urow['acces_au_site']), $templateCode);
		$templateCode = str_replace('<%%GOOGLEMAP(acces_au_site)%%>', get_embed('googlemap', $urow['acces_au_site'], '480', '360'), $templateCode);
		$templateCode = str_replace('<%%GOOGLEMAPTHUMB(acces_au_site)%%>', thisOr(get_embed('googlemap', $urow['acces_au_site'], '480', '360', 'thumbnail_url'), 'blank.gif'), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(type_de_site)%%>', safe_html($urow['type_de_site']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(type_de_site)%%>', html_attr($row['type_de_site']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(type_de_site)%%>', urlencode($urow['type_de_site']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(nom_du_responsable)%%>', safe_html($urow['nom_du_responsable']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(nom_du_responsable)%%>', html_attr($row['nom_du_responsable']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(nom_du_responsable)%%>', urlencode($urow['nom_du_responsable']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(email_du_responsable)%%>', safe_html($urow['email_du_responsable']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(email_du_responsable)%%>', html_attr($row['email_du_responsable']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(email_du_responsable)%%>', urlencode($urow['email_du_responsable']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Telephone_du_responsable)%%>', safe_html($urow['Telephone_du_responsable']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Telephone_du_responsable)%%>', html_attr($row['Telephone_du_responsable']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Telephone_du_responsable)%%>', urlencode($urow['Telephone_du_responsable']), $templateCode);
		if($AllowUpdate || $AllowInsert) {
			$templateCode = str_replace('<%%HTMLAREA(Commentaires)%%>', '<textarea name="Commentaires" id="Commentaires" rows="5">' . html_attr($row['Commentaires']) . '</textarea>', $templateCode);
		}else{
			$templateCode = str_replace('<%%HTMLAREA(Commentaires)%%>', '<div id="Commentaires" class="form-control-static">' . $row['Commentaires'] . '</div>', $templateCode);
		}
		$templateCode = str_replace('<%%VALUE(Commentaires)%%>', nl2br($row['Commentaires']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Commentaires)%%>', urlencode($urow['Commentaires']), $templateCode);
	}else{
		$templateCode = str_replace('<%%VALUE(id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(nom_du_site)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(nom_du_site)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(adresse_postale)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(adresse_postale)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(acces_au_site)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(acces_au_site)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%GOOGLEMAP(acces_au_site)%%>', '', $templateCode);
		$templateCode = str_replace('<%%GOOGLEMAPTHUMB(acces_au_site)%%>', 'blank.gif', $templateCode);
		$templateCode = str_replace('<%%VALUE(type_de_site)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(type_de_site)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(nom_du_responsable)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(nom_du_responsable)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(email_du_responsable)%%>', 'adresse@email.com', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(email_du_responsable)%%>', urlencode('adresse@email.com'), $templateCode);
		$templateCode = str_replace('<%%VALUE(Telephone_du_responsable)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Telephone_du_responsable)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%HTMLAREA(Commentaires)%%>', '<textarea name="Commentaires" id="Commentaires" rows="5"></textarea>', $templateCode);
	}

	// process translations
	foreach($Translation as $symbol=>$trans) {
		$templateCode = str_replace("<%%TRANSLATION($symbol)%%>", $trans, $templateCode);
	}

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if($_REQUEST['dvprint_x'] == '') {
		$templateCode .= "\n\n<script>\$j(function() {\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption) {
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id) {
			$templateCode.="\n\tif(document.getElementById('email_du_responsableEdit')) { document.getElementById('email_du_responsableEdit').style.display='inline'; }";
			$templateCode.="\n\tif(document.getElementById('email_du_responsableEditLink')) { document.getElementById('email_du_responsableEditLink').style.display='none'; }";
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('site_compostage');
	if($selected_id) {
		$jdata = get_joined_record('site_compostage', $selected_id);
		if($jdata === false) $jdata = get_defaults('site_compostage');
		$rdata = $row;
	}
	$templateCode .= loadView('site_compostage-ajax-cache', array('rdata' => $rdata, 'jdata' => $jdata));

	// hook: site_compostage_dv
	if(function_exists('site_compostage_dv')) {
		$args=array();
		site_compostage_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}
?>