<?php
// This script and data application were generated by AppGini 5.82
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/site_compostage.php");
	include("$currDir/site_compostage_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('site_compostage');
	if(!$perm[0]) {
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "site_compostage";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = array(
		"`site_compostage`.`id`" => "id",
		"`site_compostage`.`nom_du_site`" => "nom_du_site",
		"`site_compostage`.`adresse_postale`" => "adresse_postale",
		"`site_compostage`.`acces_au_site`" => "acces_au_site",
		"`site_compostage`.`type_de_site`" => "type_de_site",
		"`site_compostage`.`nom_du_responsable`" => "nom_du_responsable",
		"`site_compostage`.`email_du_responsable`" => "email_du_responsable",
		"`site_compostage`.`Telephone_du_responsable`" => "Telephone_du_responsable",
		"`site_compostage`.`Commentaires`" => "Commentaires",
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(
		1 => '`site_compostage`.`id`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => 5,
		6 => 6,
		7 => 7,
		8 => 8,
		9 => 9,
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = array(
		"`site_compostage`.`id`" => "id",
		"`site_compostage`.`nom_du_site`" => "nom_du_site",
		"`site_compostage`.`adresse_postale`" => "adresse_postale",
		"`site_compostage`.`acces_au_site`" => "acces_au_site",
		"`site_compostage`.`type_de_site`" => "type_de_site",
		"`site_compostage`.`nom_du_responsable`" => "nom_du_responsable",
		"`site_compostage`.`email_du_responsable`" => "email_du_responsable",
		"`site_compostage`.`Telephone_du_responsable`" => "Telephone_du_responsable",
		"`site_compostage`.`Commentaires`" => "Commentaires",
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters = array(
		"`site_compostage`.`id`" => "ID",
		"`site_compostage`.`nom_du_site`" => "Nom du site",
		"`site_compostage`.`adresse_postale`" => "Adresse du site",
		"`site_compostage`.`acces_au_site`" => "carte d\'acc&#232;s du site",
		"`site_compostage`.`type_de_site`" => "Type de site",
		"`site_compostage`.`nom_du_responsable`" => "Nom du responsable",
		"`site_compostage`.`email_du_responsable`" => "Email du responsable",
		"`site_compostage`.`Telephone_du_responsable`" => "Telephone du responsable",
		"`site_compostage`.`Commentaires`" => "Commentaires",
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS = array(
		"`site_compostage`.`id`" => "id",
		"`site_compostage`.`nom_du_site`" => "nom_du_site",
		"`site_compostage`.`adresse_postale`" => "adresse_postale",
		"`site_compostage`.`acces_au_site`" => "acces_au_site",
		"`site_compostage`.`type_de_site`" => "type_de_site",
		"`site_compostage`.`nom_du_responsable`" => "nom_du_responsable",
		"`site_compostage`.`email_du_responsable`" => "email_du_responsable",
		"`site_compostage`.`Telephone_du_responsable`" => "Telephone_du_responsable",
		"`site_compostage`.`Commentaires`" => "Commentaires",
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array();

	$x->QueryFrom = "`site_compostage` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = false;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "site_compostage_view.php";
	$x->RedirectAfterInsert = "site_compostage_view.php?SelectedID=#ID#";
	$x->TableTitle = "Site compostage";
	$x->TableIcon = "resources/table_icons/google_map.png";
	$x->PrimaryKey = "`site_compostage`.`id`";

	$x->ColWidth   = array(  150, 150, 150, 150, 150, 150);
	$x->ColCaption = array("Nom du site", "Adresse du site", "carte d'acc&#232;s du site", "Type de site", "Nom du responsable", "Email du responsable");
	$x->ColFieldName = array('nom_du_site', 'adresse_postale', 'acces_au_site', 'type_de_site', 'nom_du_responsable', 'email_du_responsable');
	$x->ColNumber  = array(2, 3, 4, 5, 6, 7);

	// template paths below are based on the app main directory
	$x->Template = 'templates/site_compostage_templateTV.html';
	$x->SelectedTemplate = 'templates/site_compostage_templateTVS.html';
	$x->TemplateDV = 'templates/site_compostage_templateDV.html';
	$x->TemplateDVP = 'templates/site_compostage_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HighlightColor = '#FFF0C2';
	$x->HasCalculatedFields = false;

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))) { $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])) { // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `site_compostage`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='site_compostage' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])) { // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `site_compostage`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='site_compostage' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3) { // view all
		// no further action
	}elseif($perm[2]==0) { // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`site_compostage`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: site_compostage_init
	$render=TRUE;
	if(function_exists('site_compostage_init')) {
		$args=array();
		$render=site_compostage_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: site_compostage_header
	$headerCode='';
	if(function_exists('site_compostage_header')) {
		$args=array();
		$headerCode=site_compostage_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode) {
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: site_compostage_footer
	$footerCode='';
	if(function_exists('site_compostage_footer')) {
		$args=array();
		$footerCode=site_compostage_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode) {
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>