<?php
// This script and data application were generated by AppGini 5.82
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/transferts.php");
	include("$currDir/transferts_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('transferts');
	if(!$perm[0]) {
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "transferts";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = array(
		"`transferts`.`id`" => "id",
		"IF(    CHAR_LENGTH(`site_compostage1`.`nom_du_site`), CONCAT_WS('',   `site_compostage1`.`nom_du_site`), '') /* Sur le site */" => "sur_le_site",
		"IF(    CHAR_LENGTH(`membres1`.`Nom`) || CHAR_LENGTH(`membres1`.`prenom`), CONCAT_WS('',   `membres1`.`Nom`, `membres1`.`prenom`), '') /* Par le technicien */" => "par_le_membre",
		"DATE_FORMAT(`transferts`.`jour_heure`, '%Y/%m/%d')" => "jour_heure",
		"`transferts`.`du_bac`" => "du_bac",
		"`transferts`.`vers_bac`" => "vers_bac",
		"`transferts`.`quantite`" => "quantite",
		"`transferts`.`cree_par`" => "cree_par",
		"`transferts`.`date_maj`" => "date_maj",
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(
		1 => '`transferts`.`id`',
		2 => '`site_compostage1`.`nom_du_site`',
		3 => 3,
		4 => '`transferts`.`jour_heure`',
		5 => 5,
		6 => 6,
		7 => '`transferts`.`quantite`',
		8 => 8,
		9 => '`transferts`.`date_maj`',
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = array(
		"`transferts`.`id`" => "id",
		"IF(    CHAR_LENGTH(`site_compostage1`.`nom_du_site`), CONCAT_WS('',   `site_compostage1`.`nom_du_site`), '') /* Sur le site */" => "sur_le_site",
		"IF(    CHAR_LENGTH(`membres1`.`Nom`) || CHAR_LENGTH(`membres1`.`prenom`), CONCAT_WS('',   `membres1`.`Nom`, `membres1`.`prenom`), '') /* Par le technicien */" => "par_le_membre",
		"DATE_FORMAT(`transferts`.`jour_heure`, '%Y/%m/%d')" => "jour_heure",
		"`transferts`.`du_bac`" => "du_bac",
		"`transferts`.`vers_bac`" => "vers_bac",
		"`transferts`.`quantite`" => "quantite",
		"`transferts`.`cree_par`" => "cree_par",
		"`transferts`.`date_maj`" => "date_maj",
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters = array(
		"`transferts`.`id`" => "ID",
		"IF(    CHAR_LENGTH(`site_compostage1`.`nom_du_site`), CONCAT_WS('',   `site_compostage1`.`nom_du_site`), '') /* Sur le site */" => "Sur le site",
		"IF(    CHAR_LENGTH(`membres1`.`Nom`) || CHAR_LENGTH(`membres1`.`prenom`), CONCAT_WS('',   `membres1`.`Nom`, `membres1`.`prenom`), '') /* Par le technicien */" => "Par le technicien",
		"`transferts`.`jour_heure`" => "Jour heure",
		"`transferts`.`du_bac`" => "Du bac",
		"`transferts`.`vers_bac`" => "Vers bac",
		"`transferts`.`quantite`" => "Quantite",
		"`transferts`.`cree_par`" => "Cree par",
		"`transferts`.`date_maj`" => "Date maj",
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS = array(
		"`transferts`.`id`" => "id",
		"IF(    CHAR_LENGTH(`site_compostage1`.`nom_du_site`), CONCAT_WS('',   `site_compostage1`.`nom_du_site`), '') /* Sur le site */" => "sur_le_site",
		"IF(    CHAR_LENGTH(`membres1`.`Nom`) || CHAR_LENGTH(`membres1`.`prenom`), CONCAT_WS('',   `membres1`.`Nom`, `membres1`.`prenom`), '') /* Par le technicien */" => "par_le_membre",
		"DATE_FORMAT(`transferts`.`jour_heure`, '%Y/%m/%d')" => "jour_heure",
		"`transferts`.`du_bac`" => "du_bac",
		"`transferts`.`vers_bac`" => "vers_bac",
		"`transferts`.`quantite`" => "quantite",
		"`transferts`.`cree_par`" => "cree_par",
		"`transferts`.`date_maj`" => "date_maj",
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array('sur_le_site' => 'Sur le site', 'par_le_membre' => 'Par le technicien', );

	$x->QueryFrom = "`transferts` LEFT JOIN `site_compostage` as site_compostage1 ON `site_compostage1`.`id`=`transferts`.`sur_le_site` LEFT JOIN `membres` as membres1 ON `membres1`.`id`=`transferts`.`par_le_membre` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = false;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "transferts_view.php";
	$x->RedirectAfterInsert = "transferts_view.php?SelectedID=#ID#";
	$x->TableTitle = "Transferts";
	$x->TableIcon = "resources/table_icons/arrow_switch.png";
	$x->PrimaryKey = "`transferts`.`id`";

	$x->ColWidth   = array(  150, 150, 150, 150, 150, 150);
	$x->ColCaption = array("Sur le site", "Par le technicien", "Jour heure", "Du bac", "Vers bac", "Quantite");
	$x->ColFieldName = array('sur_le_site', 'par_le_membre', 'jour_heure', 'du_bac', 'vers_bac', 'quantite');
	$x->ColNumber  = array(2, 3, 4, 5, 6, 7);

	// template paths below are based on the app main directory
	$x->Template = 'templates/transferts_templateTV.html';
	$x->SelectedTemplate = 'templates/transferts_templateTVS.html';
	$x->TemplateDV = 'templates/transferts_templateDV.html';
	$x->TemplateDVP = 'templates/transferts_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HighlightColor = '#FFF0C2';
	$x->HasCalculatedFields = false;

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))) { $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])) { // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `transferts`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='transferts' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])) { // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `transferts`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='transferts' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3) { // view all
		// no further action
	}elseif($perm[2]==0) { // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`transferts`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: transferts_init
	$render=TRUE;
	if(function_exists('transferts_init')) {
		$args=array();
		$render=transferts_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: transferts_header
	$headerCode='';
	if(function_exists('transferts_header')) {
		$args=array();
		$headerCode=transferts_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode) {
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: transferts_footer
	$footerCode='';
	if(function_exists('transferts_footer')) {
		$args=array();
		$footerCode=transferts_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode) {
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>