<?php

	// IMPORTANT:
	// ==========
	// When translating, only translate the strings that are
	// TO THE RIGHT OF the arrow sign (=>).
	//
	// Do NOT translate the strings between square brackets ([]) or (<>)
	// =====================================================
	$ReportTranslation = array(
		'back' => "Retour",
		'print report' => "Imprimer Rapport",
		'export report to csv file' => "Exporter en CSV",
		'records' => "<n> enregistrements",
		'period from to' => "Periode de <FROM> a <TO>",
		'change' => "Modifier",
		'report configuration' => "Configuration du rapport",
		'report period' => "Période du rapport ",
		'month to date' => "Début du mois",
		'month to date description' => "Inclure les données depuis le début du mois. Comparer avec la même période du mois précédent et la même période de l'année précédente.",
		'current month' => "Mois courant",
		'current month description' => "Inclure les données de tout le mois en cours. Comparer avec le mois précédent et le même mois de l'année précédente.",
		'last month' => "Mois dernier",
		'last month description' => "Inclure les données du mois dernier. Comparer avec le mois précédent et le même mois de l'année dernière.",
		'quarter to date' => "Trimestre à ce jour",
		'quarter to date description' => "Inclure les données du trimestre à ce jour. Comparer avec la même période du trimestre précédent et la même période de l'année précédente.",
		'current quarter' => "Trimestre en cours",
		'current quarter description' => "Inclure les données du trimestre en cours. Comparer avec le dernier et le même trimestre de l'année précédente.",
		'last quarter' => "Dernier Trimestre",
		'last quarter description' => "Inclure les données du dernier trimestre. Comparer avec le trimestre précédent et le même trimestre de l'année précédente.",
		'year to date' => "Depuis début année",
		'year to date description' => "Inclure les données depuis le début de l'année. Comparer avec la même période de l'année précédente et la même période de l'année précédente.",
		'current year' => "Année courante",
		'current year description' => "Inclure les données de l'année en cours. Comparer avec l'année dernière et l'année précédente.",
		'last year' => "Année précédente",
		'last year description' => "Inclure les données de l'année dernière. Comparer avec les deux années précédentes.",
		'comparison period 1' => "Comparaison Periode 1",
		'comparison period 2' => "Comparaison Periode 2",
		'from' => "De",
		'to' => "à",
		'order by' => "Trier par",
		'descending' => "Descendant",
		'ascending' => "Ascendant",
		'appearance' => "Apparence (appliquer)",
		'show row numbers' => "Afficher les numéros de ligne",
		'alignment of label column' => "Alignement de la colonne <LABEL>",
		'alignment of other columns' => "Alignement des autres colonnes",
		'apply' => "Appliquer",
		'close' => "Fermer",
		'charts-color-theme' => 'Charts color theme',
		'rainbow' => 'Rainbow',
		'reds' => 'Red shades',
		'oranges' => 'Orange shades',
		'yellows' => 'Yellow shades',
		'greens' => 'Green shades',
		'blues' => 'Blue shades',
		'violets' => 'Violet shades',
		'grays' => 'Gray shades',
		'barchart-orientation' => 'Bar chart orientation',
		'barchart-aspect-ratio' => 'Bar chart aspect ratio (height : width)',
		'barchart-bar-width' => 'Bars width in the bar chart (pixels)',
		'barchart-bar-spacing' => 'Bars spacing in the bar chart (pixels)',
		'barchart-bar-width-default-hint' => 'A value of 0 (the default) sets the bar width automatically.',
		'barchart-width' => 'Width of bar chart',
		'piechart-width' => 'Width of pie charts',
		'piechart-labels' => 'Labels on pie charts',
		'labels' => 'Labels',
		'labels-values' => 'Labels et valeurs',
		'labels-percentages' => 'Labels et pourcentages',
		'labels-values-percentages' => 'Labels, valeurs et pourcentages',
		'automatic' => 'Automatique',
		'loading report header' => 'Loading report header ...',
		'loading report footer' => 'Loading report footer ...',
	);